---
title: "Outline"
author: "Gonzalo García-Castro"
date: "5/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Aim: 4,000 words

# Introduction (1,250 words)

## Monolingual vocabulary acquisition (300 words)

* Participant-level predictors: age, sex, SES, quantity and quality of input
* Word-level predictors: grammatical class, frequency, length, phonological neighbourhood density

## Bilingual vocabulary acquisition (800 words)

* How bilinguals differ from monolinguals
* How the specific pair of languages they learn impacts bilingual vocabulary acquisition: Floccia et al. (2018)
* We suggest that cognates are, on average, acquired earlier than non-cognates.
* We suggest that this facilitation effect is due to infants activating a familiar word form when hearing its form-similar translation equivalent in presence of their shared referent.
* This effect can only take place once one of the forms of the translation equivalent in one language has been acquired. When acquiring the other form of the translation equivalent in the other language, form-similar should facilitate the process. Since words in the dominant language are more likely to be acquired first, the effect of cognateness should be larger in the non-dominant language (i.e., language of least exposure) than in the dominant language (language of most exposure).


## The present study (150 words)

* We compared the acquisition trajectories of cognate and non-cognate translation equivalents using vovcabulary data from bilinguals learning Catalan and Spanish.
* We hypothesised that (1) cognates are acquired earlier than non-cognates, and (2) that this effect is larger for items that belong to the language of least exposure


# Methods (750 words)

## Participants (250 words)

* Brief description of the sample (age, sex, location, SES, etc.)
* Ethics
* Language profile
* Sample sizes

## Vocabulary inventory (250 words)

* What the questionnaire looks like (online, list of words, similar to CDI, etc)
* Description of the items included (frequency, grammatical class)
* Randomisation (short versions)

## Data analysis (250 words)

* Dependent variable
* Predictors
* Model


# Results (1,000 words)

## Comprehension (500 words)

## Production (500 words)


# Discussion (1,000 words)


# Acknowledgements


# References

# Appendix

## Appendix 1: Participant information

## Appendix 2: Questionnaire information

## Appendix 3: Model
