---
---

# Introduction

Before the end of their first year of life, infants start directing their gaze to some object when hearing their labels, according to both experimental data [@jusczyk1995infants; @tincoff1999some; @bergelson2012months] and parental reports [e.g., @fenson1994variability]. During the last half of their second year, they acquire new words at an increasingly fast rate [@fenson1994variability; @bloom2002children; @bergelson2020comprehension]. Despite the considerable variation in children's trajectories of vocabulary growth, such trajectories seem quite consistent across languages [@braginsky2019consistency]. Nonetheless, most of the literature on early word acquisition has been conducted on monolingual children, and does not address the problem of how bilinguals--who represent a substantial proportion of the population in most societies--acquire words at early ages.


There is evidence that bilinguals know less words in each of their languages than monolinguals, but also that both groups know a similar amount of words when the two languages are aggregated. For example, @hoff2012dual found that English-Spanish bilingual toddlers in South Florida knew less words in English than monolinguals (who only learnt English). In contrast, both groups knew a similar total amount of words, when both English and Spanish vocabularies were counted together. Other studies have provided converging evidence that bilinguals know a similar--or even larger--number of words than monolinguals, only when the languages are aggregated [@oller2002language; @pearson1994patterns; @pearson1993lexical; @patterson2004comparing; @patterson2004bilingual; @smithson2014bilingualism; @petitto2001bilingual; @gonzalez2020bilingual; @fabian2016investigating]. While these studies have mostly relied on samples of bilingual children learning two relatively distant languages (as it is the case of English and Spanish) it is unclear whether children learning typologically more similar languages also know less words in each of their languages than monolinguals. What role could linguistic distance play during early vocabulary growth?


For a given set of concepts, bilingual children may be exposed to two distinct sets of word-forms--one in each language. Depending on the linguistic distance between both languages, the two sets of words may overlap in varying degrees. Particularly, when both languages are linguistically close, like Spanish and Catalan (both Roman languages), they are more likely to share a larger amount of cognates (i.e., form-similar translation equivalents) than two linguistically distant languages, like Spanish and English--one Roman, the other Germanic. For instance, in the presence of a door, a Spanish-Italian (or a Spanish-Catalan) bilingual might hear *puerta* and *porta* (cognates), whereas a Spanish-English bilingual might hear *puerta* and *door* (non-cognates). It could be the case that mapping two phonologically similar labels (cognates, like *puerta*-*porta*) onto the same referent is easier than doing the same with two phonologically dissimilar labels (non-cognates, like *puerta* and *door*). If cognates are easier to acquire than non-cognates, bilinguals learning a pair of languages that share a high proportion of cognates should benefit more often from this facilitation effect than those learning a pair of languages with a lower proportion of cognates, and should therefore show larger vocabulary sizes.



A recent study by @floccia2018introduction provided evidence in line with this claim. The authors collected vocabulary data on word comprehension and production from 372 24-month-old bilingual toddlers in the United Kingdom who were learning English and an additional language. The additional language was one a pool of 13 typologically diverse languages: Bengali, Cantonese Chinese, Dutch, French, German, Greek, Hindi/Urdu, Italian, Mandarin Chinese, Polish, Portuguese, Spanish and Welsh. The authors calculated the average phonological similarity between the words in each of these additional languages and their translation equivalents in English. Phonological similarity was measuring by computing the Levenshtein distance between each cross-language pair of phonological transcriptions. The Levenshtein distance is a metric that computes the edit distance between two strings by counting the smallest number of insertions, deletions and substitutions one of the strings has to go through to become identical to the other [@levenshtein1966binary]. Floccia et al. divided the resulting score by the length of the longest string to bound the similarity scores between 0 and 1, and then entered this variable as a predictor as they modelled participants' vocabulary sizes. Among other findings, the authors reported an increase in productive vocabulary size in the additional language associated with an increase in the average phonological similarity between the translation equivalents of each language pair. For example, English-Dutch bilinguals (22.14% phonological similarity), were able to produce more Dutch words than English-Mandarin bilinguals (1.97% phonological similarity) were able to produce in Mandarin.


Floccia et al. pointed to *parallel activation* as the main mechanism underpinning their results. The parallel activation hypothesis suggests that bilinguals activate both languages simultaneously during speech production or comprehension. This phenomenon is the result of the activation of lexical representations in both languages, even when only one is in use during production [@costa2000cognate; @hoshino2008cognate] or comprehension [@thierry2007brain]. One of the clearest examples of parallel activation was provided by @costa2000cognate. In this study, Catalan-Spanish monolingual and bilingual adults were asked to name pictures of common objects in Spanish. In half of the trials, the object labels were cognates in Spanish and Catalan (*árbol*-*arbre*, translations of *tree*), whereas in the other half of the trials labels were non-cognates (*mesa*-*taula*, translations of *table*). Bilinguals named cognate pictures faster than non-cognate pictures, even after adjusting for the lexical frequency of the items. Importantly, Spanish monolinguals did not show this effect. These results suggest that, for the bilinguals, Catalan phonology was activated during the production of Spanish words, facilitating the naming of cognate pictures. Several recent studies have also provided similar evidence in comprehension in children [e.g., @von2012language; @poulin2013lexical]. Parallel activation is therefore a plausible mechanism to account for Floccia et al.'s results: cognates increase the amount of activation in both languages, facilitating word acquisition. Therefore, children learning language pairs with a larger proportion of cognates are predicted to show larger vocabulary sizes. If cognates are the reason for this facilitation effect, it could be predicted that cognates are acquired earlier than non-cognates. Likely as it might seem, an earlier age of acquisition for cognates is not the only scenario where Floccia et al.'s results are account for.
For example, languages that share more cognates might also share a larger overlap in their phonemic inventories, which could facilitate the acquisition of all words, regardless of their cognate status.


However, the evidence on an earlier age of acquisition for cognates compared to non-cognates is scarce. To the best of our knowledge only two studies have provided direct data on this issue. First, @bosch2014first used vocabulary parental reports (152 lexical items) from 48 Catalan-Spanish bilinguals aged 18 months, and found that cognates represented a larger proportion of participant's vocabulary than non-cognates. Second, @schelletter2002effect reported a longitudinal single case of one English-German bilingual who produced cognates earlier than non-cognates, on average. The low sample size in these studies make it challenging to draw strong conclusions about the effect of cognateness in vocabulary growth. Floccia et al.'s estimates are statically more reliable given their (much larger) sample size, but their study was not aimed at testing the effect of cognateness on age of acquisition directly. In their discussion the authors state the following (pp. 70):


> "This  finding  also  provides  support  to  the  proposal  that  the  cognate advantage is due to cognates being acquired before non-cognates in early childhood (Costa et al., 2016), leading to an ease of processing later in life."


We identify two main reasons why we cannot conclude an earlier age of acquisition for cognates than for non cognate from Floccia et al.'s results. First, the response variable used was the proportion of words each participant understood and/or produced, from the list of lexical items in the vocabulary checklists. By aggregating the responses from all items into a single datum per child, information about the acquisition status of cognates vs. non-cognates was lost. Second, all participants were aged 24 months, meaning that even if the unaggregated responses to individual items were included as response variable, the possible effect of cognateness could only be interpreted as an increase or decrease in the likelihood of participants at this age to have acquired each item, and not as an increase or decrease in the age of acquisition of such item. In summary, the evidence supporting an earlier age of acquisition of cognates vs. non-cognates presents some limitations that prevents drawing sound conclusions about this effect. 


Another worth-mentioning finding in Floccia et al. is that the increase in vocabulary size associated with linguistic similarity was larger in the additional language vocabulary than in English vocabulary. Most participants in their sample were English-dominant, meaning that their relative amount of exposure to English was larger than in the additional language. Given that the relative amount of exposure to a given language is a strong predictor of children's vocabulary size in that language [e.g., @cattani2014much; @thordardottir2006bilingual], participants may have, on average, learnt the English word-form of translation equivalents earlier than the word-form in the additional language.  If this is the case, then the acquisition of English words by English-dominant participants would rarely benefit from their cognate status (the other word-form is not available yet), while the acquisition of words in the additional language would benefit from their phonological similarity with the (available) English form.


The aim of this study is to investigate the role of cognateness in bilingual word acquisition. We hypothesised that cognate words would be acquired earlier than non-cognate word, and that this difference would be larger in participants with lower exposure to the language such word belongs to. Using an designed online vocabulary checklist--carefully designed specifically for this study--we collected data from a sample of bilinguals aged 10 to 36 months learning Catalan and/or Spanish, with varying degrees of exposure to each language. We then modelled the probability of participants being reported by their parents to understand and/or say each word in the checklist, conditional to its cognate status in Catalan and Spanish and participants' degree of exposure to the corresponding language, while adjusting for participants' age and the item's lexical frequency.






