---
title: "Results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Results


## Hypothesis 1: Are cognates acquired ealier?


#### Comprehensive data


```{r compselection, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

# compare models
selection_comp %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  select(model, df, aic, bic, log_lik, l_ratio, p_value) %>% 
  mutate(p_value = printp(p_value)) %>% 
  gt() %>% 
  fmt_number(columns = 1:2, decimals = 0) %>%
  fmt_number(columns = 3:6) %>%
  fmt_missing(columns = c(6:7), missing_text = "-") %>% 
  cols_label(model = "Model",
             df = md("*df*"),
             aic = "AIC",
             bic = "BIC",
             log_lik = "Log. Likelihood",
             l_ratio = "Likelihood ratio",
             p_value = md("*p*"))

```



```{r companova, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

anova_comp %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  rownames_to_column("term") %>% 
  mutate(p_value = printp(p_value)) %>% 
  gt() %>% 
  fmt_number(columns = 2, decimals = 0) %>%
  fmt_number(columns = 3:4) %>%
  cols_label(term = "Term",
             num_df = md("Num. *df*"),
             den_df = md("Den. *df*"),
             f_value = md("*F*"),
             p_value = md("*p*")) 

summary_comp <- summary(fit4_comp)

```



```{r comppredictions, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}


dat_comp %>% 
    arrange(item, age_bin, item_dominance) %>% 
    ggplot(aes(age_bin, proportion, colour = interaction(cognate, item_dominance, sep = " - "))) +
    geom_line(data = comp_preds, aes(age_bin, proportion), size = 1) + 
    stat_summary(fun = "mean", geom = "point", shape = 1, size = 3) +
    labs(x = "Age (months)", y = "Proportion", colour = "Cognateness") +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(breaks = unique(dat_prod$age_bin), labels = bins_interest,
                       guide = guide_axis(n.dodge = 2)) +
    theme_bw() +
    theme(text = element_text(size = 12),
          legend.position = "right",
          legend.title = element_blank(),
          axis.text = element_text(colour = "black")) +
  ggsave(here("Figures", "predictions_comp.png"))

```



### Productive data


```{r prodselection, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

# compare models
selection_prod %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  select(model, df, aic, bic, log_lik, l_ratio, p_value) %>% 
  mutate(p_value = printp(p_value)) %>% 
  gt() %>% 
  fmt_number(columns = 1:2, decimals = 0) %>%
  fmt_number(columns = 3:6) %>%
  fmt_missing(columns = c(6:7), missing_text = "-") %>% 
  cols_label(model = "Model",
             df = md("*df*"),
             aic = "AIC",
             bic = "BIC",
             log_lik = "Log. Likelihood",
             l_ratio = "Likelihood ratio",
             p_value = md("*p*"))

```



```{r prodanova, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

anova_prod %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  rownames_to_column("term") %>% 
  mutate(p_value = printp(p_value)) %>% 
  gt() %>% 
  fmt_number(columns = 2, decimals = 0) %>%
  fmt_number(columns = 3:4) %>%
  cols_label(term = "Term",
             num_df = md("Num. *df*"),
             den_df = md("Den. *df*"),
             f_value = md("*F*"),
             p_value = md("*p*")) 

```



```{r prodpredictions, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

dat_prod %>% 
    arrange(item, age_bin, item_dominance) %>% 
    ggplot(aes(age_bin, proportion, colour = interaction(cognate, item_dominance, sep = " - "))) +
    geom_line(data = prod_preds, aes(age_bin, proportion), size = 1) + 
    stat_summary(fun = "mean", geom = "point", shape = 1, size = 3) +
    labs(x = "Age (months)", y = "Proportion", colour = "Cognateness") +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(breaks = unique(dat_prod$age_bin), labels = bins_interest,
                       guide = guide_axis(n.dodge = 2)) +
    theme_bw() +
    theme(text = element_text(size = 12),
          legend.position = "right",
          legend.title = element_blank(),
          axis.text = element_text(colour = "black")) +
  ggsave(here("Figures", "predictions_prod.png"))


```



```{r ranefs, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

ggplot(rancoefs, aes(xmid_intercept, xmid_item_dominance1, colour = cognate, fill = cognate)) +
  facet_wrap(type~cognate, scales = "free") +
  geom_point(size = 3, alpha = 0.5, shape = 1, colour = "grey") +
  geom_smooth(method = "lm", formula = y~x) +
  labs(x = "Mid-point intercept", y = "Item dominance slope on Mid-point", colour = "Cognateness") +
  scale_colour_brewer(palette = "Set1") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_continuous() + 
  theme_bw() +
  theme(legend.background = element_rect(fill = NA),
        legend.title = element_blank(),
        legend.key = element_rect(fill = NA),
        legend.position = "none")

```

## Hypothesis 2


```{r aoafig, echo=FALSE, message=TRUE, warning=FALSE, paged.print=FALSE}

ggplot(aoas, aes(xmid, fct_rev(item_dominance))) +
    facet_grid(cognate~type) +
    annotate(geom = "rect", xmin = 0, xmax = 10, ymin = -Inf, ymax = Inf, colour = NA, fill = "orange", alpha = 0.25)  +
    #annotate(geom = "text", x = 5, y = 0, label = "Range of observed data", size = 7) +
    geom_line(aes(group = te), colour = "black", alpha = 0.05) +
    geom_violin(fill = "grey30", colour = "grey30", width = 0.5) +
    geom_boxplot(width = 0.25, fill = "white", colour = "black", outlier.colour = NA) +
    labs(x = "Age (months)", y = "Item dominance", fill = "Item dominance", colour = "Item dominance") +
    theme_bw() +
    scale_x_continuous(breaks = -5:15, labels = bins_expanded, guide = guide_axis(n.dodge = 1)) +
    theme(legend.title = element_blank(),
          legend.position = "none",
          legend.background = element_rect(fill = NA),
          axis.text = element_text(colour = "black"),
          axis.text.x = element_text(size = 8),
          axis.title.y = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank()) +
  ggsave(here("Figures", "aoa.png"))

```