---
title: "Introduction"
author: "Gonzalo García-Castro"
date: "3/17/2021"
output:
  word_document:
    reference_docx: trajectories_template.docx
  pdf_document:
      latex_engine: xelatex
bibliography: trajectories.bib
csl: apa6.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

<<<<<<< HEAD
<<<<<<< HEAD
Before the end of their first year of life, infants are able to encode sound patterns [@jusczyk1995infants; @tincoff1999some] and associate them with their referents [@bergelson2012months]. Later on, infants begin to represent those word-forms with finer phonological detail [e.g. @werker2002infants], and from 18 to 24 months of age, they acquire new words at an increasingly fast rate [@fenson1994variability; @bloom2002children; @bergelson2020comprehension]. The type of words acquired earlier at these ages provides  information about the mechanisms and biases that constrain early vocabulary growth. Recent works show that the words that are acquired  are nouns, highly concrete words, or words that appear in short sentences, an that this pattern is relatively consistent across languages [@braginsky2019consistency]. Most of the literature on early word acquisition has been conducted on monolingual children. However, a substantial proportion of children around the world are exposed to two languages from birth (bilinguals, henceforth). Given that the relative amount of input a child receives in each language is a strong predictor of vocabulary size [e.g., @cattani2014much; @thordardottir2006bilingual; @david2008individual; @floccia2018introduction], generalising the aforementioned developmental patterns of word acquisition to bilinguals is challenging.
=======
Before the end of their first year of life, infants are able to encode sound patterns [@jusczyk1995infants; @tincoff1999some] and associate them with their referents [@bergelson2012months]. Later on, infants begin to represent those word-forms with finer phonological detail [e.g. @werker2002infants], and during the last half of their second year, they acquire new words at an increasingly fast rate [@fenson1994variability; @bloom2002children; @bergelson2020comprehension]. Despite the considerable variation in children's trajectories of vocabulary growth, such trajectories seem quite consistent across languages [@braginsky2019consistency]. Nonetheless, most of the literature on early word acquisition has been conducted on monolingual children, and does not address the problem of how bilinguals--who represent a substantial proportion of the populatio in most societies--acquire words at early ages.
>>>>>>> 5bf2f723b2d5290b7153be39314ed1363c7225d6


There is evidence that bilinguals know less words in each of their languages than monolinguals, but also that both groups know a similar amount of words when the two languages are aggregated. For example, @hoff2012dual found that English-Spanish bilingual toddlers in South Florida knew less words in English than monolinguals (who only learnt English). In contrast, both groups knew a similar total amount of words, when both English and Spanish vocabularies were counted together. Other studies have provided converging evidence that bilinguals know a similar--or even larger--number of words than monolinguals, only when the languages are aggregated [@oller2002language; @pearson1994patterns; @pearson1993lexical; @patterson2004comparing; @patterson2004bilingual; @smithson2014bilingualism; @petitto2001bilingual; @gonzalez2020bilingual; @fabian2016investigating]. While these studies have mostly relied on samples of bilingual children learning two relatively distant languages (as it is the case of English and Spanish) it is unclear whether children learning two more similar languages also know less words in each of their languages than monolinguals. What role could linguistic distance play during early vocabulary growth?


For a given set of concepts, bilingual children may be exposed to two distinct sets of word-forms--one in each language. Depending on the linguistic distance between both languages, the two sets of words may overlap in varying degrees. Particularly, when both languages are linguistically close, like Spanish and Catalan (both Roman languages), they are more likely to share a larger amount of cognates (i.e., form-similar translation equivalents) than two linguistically distant languages, like Spanish and English--one Roman, the other Germanic. For instance, in the presence of a door, a Spanish-Catalan bilingual might hear *puerta* and *porta* (cognates), whereas a Spanish-English bilingual might hear *puerta* and *door* (non-cognates). It could be the case that mapping two phonologically similar labels (cognates, like *puerta*-*porta*) onto the same referent is easier than doing the same with two phonologically dissimilar labels (non-cognates, like *puerta* and *door*). If cognates are easier to acquire than non-cognates, bilinguals learning a pair of languages that share a high proportion of cognates should benefit more often from this facilitation effect than those learning a pair of languages with a lower proportion of cognates, and should therefore show larger vocabulary sizes.



A recent study by @floccia2018introduction provided evidence in line with this claim. The authors collected vocabulary data from 372 24-month-old bilingual toddlers in the United Kingdom who were learning English and an additional language. The additional language was one a pool of 13 languages that differed in their phonological similarity with respect to English, such as Dutch, Italian, or Mandarin. The authors defined phonological similarity as the average edit distance (length-adjusted Levenshtein distance) between translation equivalents in each language pair. The authors reported an increase in productive vocabulary size in the additional language associated with an increase in phonological overlap between the language pair. For example, English-Dutch bilinguals (22.14% phonological similarity), were able to produce more Dutch words than English-Mandarin bilinguals (1.97% phonological similarity) were able to produce in Mandarin.


Floccia et al. pointed to *parallel activation* as the main mechanism underpinning their results. The parallel activation hypothesis suggests that bilinguals activate both languages simultaneously during speech production or comprehension. This phenomenon is the result of the activation of lexical representations in both languages, even when only one is in use during production [@costa2000cognate; @hoshino2008cognate] or comprehension [@thierry2007brain]. One of the clearest examples of parallel activation was provided by @costa2000cognate. In this study, Catalan-Spanish monolingual and bilingual adults were asked to name pictures of common objects in Catalan (their dominant language). In half of the trials, the object labels were cognates in Catalan and Spanish (*sofà*-*sofá*, translations of *sofa*), whereas in the other half of the trials labels were non-cognates (*taula*-*mesa*, translations of *table*). Bilinguals named cognate pictures faster than non-cognate pictures, even after adjusting for the lexical frequency of the items. Importantly, monolinguals did not show this effect. These results suggest that, for the bilinguals, Spanish phonology was activated during the production of Catalan words, facilitating the naming of cognate pictures. Several recent studies have also provided similar evidence in comprehension in children [e.g., @von2012language; @poulin2013lexical]. In summary, the parallel activation account of bilingual word acquisition suggests that bilinguals' vocabulary size grows faster when both languages share a high proportion of cognate translation equivalents, as a result of increased activation of word forms in both languages during speech processing.


If parallel activation plays a role during early word acquisition, it could be predicted that the age of acquisition of cognate translation equivalents is, on average, lower than that of non-cognates. However, the evidence supporting this claim is scarce. On the one hand, @bosch2014first used vocabulary parental reports (152 lexical items) from 48 Catalan-Spanish bilinguals aged 18 months, and found that cognates represented a larger proportion of participant's vocabulary than non-cognates, and @schelletter2002effect reported a longitudinal single case of an English-German bilingual who produced cognates earlier than non-cognates, on average. The low sample size in these studies make it challenging to draw strong conclusions about the effect of cognateness in vocabulary growth. On the other hand Floccia et al.'s estimates are statically more reliable given their (much larger) sample size, but their study was not aimed at testing the effect of cognateness on age of acquisition directly. We identify two main reasons why we cannot conclude an earlier age of acquisition for cognates than for non cognate from Floccia et al.'s results. First, the response variable used was the proportion of words each participant understood and/or produced, from the list of lexical items in the vocabulary checklists. By aggregating the responses from all items into a single datum per child, information about the acquisition status of cognates vs. non-cognates was lost. Second, all participants were aged 24 months, meaning that even if the unaggregated responses to individual items were included as response variable, the possible effect of cognateness could only be interpreted as an increase or decrease in the likelihood of participants at this age to have acquired each item, and not as an increase or decrease in the age of acquisition of such item. In summary, the evidence supporting an earlier age of acquisition of cognates vs. non-cognates presents some limitations that prevents drawing sound conclusions about this effect. 


Another worth-mentioning finding in Floccia et al. is that the increase in vocabulary size associated with lingusitic similarity was larger in the additional language vocabulary than in English vocabulary. Most participants in their sample were English-dominant, meaning that their relative amount of exposure to English was larger than in the additional language. Given that the relative amount of exposure to a given language is a strong predictor of children's vocabulary size in that language [e.g., @cattani2014much; @thordardottir2006bilingual], participants may have, on average, learnt the English word-form of translation equivalents earlier than the word-form in the additional language.  If this is the case, then the acquisition of English words by English-dominant participants would rarely benefit from their cognate status (the other word-form is not available yet), while the acquisition of words in the additional language would benefit from their phonological similarity with the (available) English form.


The aim of this study is to investigate the role of cognateness in bilingual word acquisition. We hypothesised that cognate words would be acquired earlier than non-cognate word, and that this difference would be larger in participants with lower exposure to the language such word belongs to. Using an *ad hoc* online vocabulary checklist, we collected data from a sample of bilinguals aged 10 to 36 months learning Catalan and/or Spanish, with varying degrees of exposure to each language. We then modelled the probability of participants being reported by their parents to understand and/or say each word in the checklist, conditional to its cognate status in Catalan and Spanish and participants' degree of exposure tto the corresponding language, while adjusting for participants' age and the item's lexical frequency.



=======
Before the end of their first year of life, infants are able to encode sound patterns [@jusczyk1995infants; @tincoff1999some] and associate them with their referents [@bergelson2012months]. During the second year, infants represent those word-forms with finer phonological detail [e.g. @werker2002infants], and from 18 to 24 months of age, they acquire new words at an increasingly faster rate [@fenson1994variability; @bloom2002children; @bergelson2020comprehension]. What words are acquired earlier at these ages provides rich information about the mechanisms and biases that constrain early vocabulary growth. For instance, @braginsky2019consistency modelled vocabulary data from a large sample of children learning a diverse pool of languages and found that, across languages, words were acquired earlier if they were nouns, were highly concrete, or appeared in short sentences on average. Despite this consistency in their trajectories of acquisition, children display large variability in the composition of their vocabulary, in part due to the diversity of their language input.

One of the causes of sources of this variability is the fact that a substantial proportion of children around the world learn to languages from birth. These children--to which we will refer as *bilinguals*--are a particular case of language learners: their linguistic input is divided into two languages. Taking into account that the relative amount of linguistic input the child receives in each language is a strong predictor of their vocabulary size [e.g., @cattani2014much; @thordardottir2006bilingual; @david2008individual; @pearson1997relation; @floccia2018introduction], one could predict that bilinguals know less words in each of their languages than their monolinguals peers. This is the case for some bilingual populations. For instance, @hoff2012dual found that English-Spanish bilingual toddlers in South Florida knew less words in English than monolinguals that only learnt English. Other studies have provided converging evidence that bilinguals and monolinguals know a similar [@oller2002language; @pearson1994patterns; @pearson1993lexical; @patterson2004comparing; @patterson2004bilingual; @smithson2014bilingualism; @junker2002expressive; @petitto2001bilingual; @gonzalez2020bilingual; @fabian2016investigating] or even larger [@de2014bilingual; @aguila2008media] amount of words, only when summing up both languages together.

A recent study by @floccia2018introduction suggests that the size of the difference between bilinguals' and monolinguals' trajectory of vocabulary growth varies considerably, conditional to the similarity between the two languages bilinguals are learning. The authors collected vocabulary data from 24 month-old bilingual toddlers in the United Kingdom, who were learning English and an additional language. The additional language was one a pool of 13 diverse languages that differed in their phonological and grammatical similarity with English (e.g., Dutch, Italian, Mandarin). Among their many findings, the authors reported a positive association between language similarity and vocabulary size. Particularly, the average phonological overlap between translation equivalents (TEs) in both languages (i.e., cognateness) predicted larger productive vocabulary sizes. For instance, children learning English and Dutch, sharing 22.14% phonological overlap, were able to produce more words than children learning English and Mandarin, only sharing 1.97% phonological overlap. These results put Hoff et al. and others' results--obtained in participants relatively distant languages--in a scenario where the differences in vocabulary size between monolinguals and bilinguals are difficult to generalise to other bilingual populations whose languages are linguistically closer. In line with these findings, @aguila2008media reported that bilingual toddlers learning Catalan and Spanish--two lexically very close languages--showed larger total vocabulary sizes than monolinguals, following a different pattern than bilinguals learning English and Spanish in @hoff2012dual.

Floccia et al. pointed to parallel activation as the main mechanism behind their results. *Parallel activation* refers to the hypothesis that bilinguals activate both languages simultaneously during speech production or comprehension. This phenomenon is understood as the result of participants activating lexical representations in both languages, even when only using one of them [@thierry2007brain; @hoshino2008cognate; @bobb2020co]. One of the clearest examples of this parallel activation was provided by @costa2000cognate. In this study, Catalan-Spanish bilingual adults were asked to name pictures of common objects in Catalan, their dominant language. In half of the trials, the names of the objects were cognates (form-similar translation equivalents) in Catalan and Spanish (*sofà*-*sofá*, translations of *sofa*), whereas in the other half of the trials the names were non-cognates (*taula*-*mesa*, translations of *table*). Participants named cognate pictures faster than non-cognate pictures, even after adjusting for the lexical frequency of the items. Importantly, monolinguals did not show this effect. The authors suggested that, in cognate trials, the phonology of the Spanish word-forms was activated and facilitated the production of the Catalan word-form. More recently, several studies have provided evidence of similar cross-language activation in children [@von2012language; @poulin2013lexical; @jardak2019labels; @bosma2020cognate]. @floccia2018introduction pointed to bilingual toddlers' vocabulary size growing faster when both languages share a high proportion of cognate TEs, hypothesising that this leads to increased parallel activation of both words forms during speech processing. But do toddlers really know enough TEs for parallel activation to be a plausible mechanism for this effect?

Despite initial claims that bilinguals do not acquire TEs during their first years of life [@volterra1978acquisition], later studies reported that not only TEs are present at early stages of lexical development, but also represent an important proportion of the early bilingual [@pearson1993lexical; @de2014bilingual; @holowka2002semantic; @junker2002expressive; @legacy2016vocabulary; @bilson2015semantic] or even trilingual [@montanari2010translation] lexicon. If parallel activation plays a role during word acquisition at these ages, it could be predicted that cognate TEs are acquired earlier than non-cognate TEs, on the assumption that their acquisition is facilitated by their co-activation during speech processing. In line with this prediction, @bosch2014first found that cognates represented a larger proportion of the productive vocabulary of bilinguals than it would be expected from data in monolingual children [see @fabian2016investigating for similar results in Portuguese-English bilinguals]. Converging evidence was also provided by @schelletter2002effect, who reported the longitudinal single case of an English-German bilingual who learnt form-similar TEs earlier than form-dissimilar TEs. Interestingly, @gampe2018bilex reported experimental data in the same direction, by using a vocabulary assessment tool in which bilingual children learning Swiss German and an additional language, were asked to select a named picture from a set of eight pictures where the remaining seven were distractors. On average, children responded more accurately to cognate items than to non-cognate trials. In summary, there is evidence that cognate TEs may be acquired earlier.

The most common notion of parallel activation in the literature, however, does not quite satisfy the explanation needed for why TEs are acquired earlier when their forms are similar across languages. Parallel activation requires the existence of two already acquired representations, one in each language, that share meaning and are activated simultaneously during speech production and comprehension. This is not the case during the acquisition of TEs. First, if no members of the TE have been acquired yet, it would be impossible that form-similarity plays any role during the acquisition of any, as no representations are available for activation during speech processing. Even if one of the members of the TE has been acquired, it is not possible to activate a second member that has not been acquired! Finally, if both members have been acquired, parallel activation is possible, but it cannot account for the acquisition of the TE, which has already been completed. If parallel activation is to play a role during the acquisition of TEs, it must be assumed that the acquisition of a word form is gradual, in line with accumulator models accounts of vocabulary acquisition [e.g., @mcmurray2007defusing; @hidaka2013computational; @mollica2017data; @kachergis2021toward], and does not require a mature representation in the lexicon. This way, once one of the members of the TE has been acquired, the exposure to the acoustic form of the other member can activate the former, and their form similarity can facilitation the acquisition of the latter.

Within each TE, members that belong to the language of higher exposure are more likely to be acquired first, thus to facilitate the later acquisition of the member in the other language. This means that, if parallel activation plays a role in the cognate facilitation effect during bilingual word acquisition, this effect must be stronger in the language of lower exposure than in the language of higher exposure. Supporting this claim, the effect of cognateness reported by Floccia et al. only reached statistical significance in the additional language, not in English, the dominant language of participants. However, not this nor the other aforementioned studies tested  the effect of cognateness on the acquisition of TEs, but rather on the overall vocabulary size of participants. From this data it is not possible to draw any conclusions about the potential role of language dominance on the cognate facilitation effect. Another reason for not drawing conclusions from @floccia2018introduction et al.'s results about how cognateness of language dominance impact the age of acquisition of TEs is that their sample consisted on 24 month-old participants only, therefore overlooking the temporal dimension of word acquisition we are interested in.

In the present study we build onto previous studies of word acquisition to extend @floccia2018introduction's findings. We collected data from a sample of children of ages ranging from 10 to 36 months learning Catalan and/or Spanish, with varying degrees of exposure to each language. We hypothesised that TEs would be acquired earlier if both the Catalan and the Spanish word-forms were cognates, compared to when they are non-cognates. We also predicted that this effect would be larger for participants whose degree of exposure to the language a given word-form belongs to is lower, compard to when their exposure to that language is higer. The reaons behind this secodn prediction is that, for the acquistion of a word-form in one language to be facilitated by the phonological activation of its TE  in the other language, such TEs must have already been acquired. Given that words are more likely to be acquired in the language of higher exposure first, and in the language of lower exposure second, the facilitation effect should, on average, take place during the acquisition of the word-form in the language of lower exposure.
>>>>>>> 3af5eed9e751f6ee24e81665fc349490defb9d42

## References




