---
title             : "The role of cross-linguistic lexical similarity on bilingual word acquisition"
shorttitle        : "Cross-linguistic similarity and  word acquisition"

author: 
  - name          : "Gonzalo Garcia-Castro"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Ramon Trias Fargas, 25-27, 08005 Barcelona, Spain"
    email         : "gonzalo.garciadecastro@upf.edu"
  - name          : "Daniela Avila-Varela"
    affiliation   : "1"
  - name          : "Nuria Sebastian-Galles"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "Center for Brain and Cognition, Universitat Pompeu Fabra, Barcelona, Spain"

authornote: |
  Campus de Ciutadella, Universitat Pompeu Fabra, 08005, Barcelona, Spain

abstract: |
  Bilinguals face the challenging task of learning words from languages with overlapping phonologies. Floccia et al. (2018) reported larger vocabulary sizes for 24-month-old bilinguals that were learning languages that shared a greater amount of cognates (e.g., English-Dutch). The mechanisms underlying this effect remain unknown. We explore two compatible scenarios. First, we test whether cognates are learnt earlier than non-cognates. This would account for the difference in vocabulary size associated to the amount of shared cognates across languages. Second, we explore the possibility that the word-forms of one language interact with those form the other language, scaffolding the acquisition of their translation equivalents when their phonologies overlap. This mechanism, in line with the parallel activation account of bilingual speech perception, would provide a plausible explanation to why cognates are acquired ealier by bilinguals. We developed an online tool to collect parental reports of receptive and productive vocabularies from children learning Catalan and/or Spanish, and present data on receptive and productive vocabulary of bilingual toddlers aged 12 to 34 months.


  <!-- https://tinyurl.com/ybremelq -->

keywords          : "lexical acquisition, vocabulary, bilingualism"
wordcount         : "X"

bibliography      : ["trajectories.bib"]

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
keep_text         : false
class             : "man"

documentclass     : "apa6"
classoption       : "man"
output            :
  papaja::apa6_pdf:
    latex_engine  : "xelatex"

  

---
 
```{r setup, include = FALSE}

knitr::opts_chunk$set(
  echo = FALSE,
  fig.align = "center",
  message = FALSE,
  warning = FALSE,
  cache.extra = knitr::rand_seed,
  out.width = "80%",
  results = "asis"
)
```

```{r packages, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

# load packages
library(papaja)
library(knitr)
library(here)

```

# Introduction

```{r introduction, child="01_introduction.Rmd"}

```


# Methods

```{r method, child="02_methods.Rmd"}

```

# Results

# Discussion

# References


\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>

\endgroup


```{r create_r-references, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

r_refs(file = "trajectories.bib")

```

