project:
  title: "cognate-beginnings"
  type: website
  output-dir: docs
  
  preview: 
    port: 3333
    browser: true
    watch-inputs: false
    navigate: true
  
  render: 
    - index.qmd
    - docs/_repo-structure.qmd
    - docs/_repro.qmd
    - docs/_data-dictionary.qmd

execute:
  freeze: auto 

website:
  twitter-card:
    creator: "@gongcastro"
    site: "@cbcUPF"
    image: https://raw.githubusercontent.com/gongcastro/gongcastro.github.io/main/assets/media/favicon.ico
  favicon: https://raw.githubusercontent.com/gongcastro/gongcastro.github.io/main/assets/media/favicon.ico
  repo-url: https://github.com/gongcastro/cognate-beginnings
  repo-actions: [edit, issue]
  page-navigation: true
  
  navbar:
    pinned: true
    background: primary
    search: false
    left:
      - text: "Home"
        file: index.qmd
      - text: "Reproducibility"
        file: docs/_repro.qmd
      - text: "Data"
        file: docs/_data-dictionary.qmd
    right:
      - icon: github
        aria-label: github
        href: https://github.com/gongcastro/cognate-beginnings

  page-footer:
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/gongcastro/cognate-beginnings)

format:
  html:
    shift-heading-level-by: 1
    theme: 
      - docs/_assets/style.scss
    toc: true
    toc-depth: 4
    retina: 3
    code-fold: true
    code-tools: true