author:
  - name: Gonzalo Garcia-Castro
    affiliations: 
      - ref: cbc
    corresponding: true
    email: gonzalo.garciadecastro@upf.edu
    
  - name: Daniela S. Avila-Varela
    affiliations: 
      - ref: cbc
      - ref: ul
  - name: Ignacio Castillejo
    affiliations: 
      - ref: uam
      
  - name: Núria Sebastian-Galles
    affiliations: 
      - ref: cbc
        
affiliations:
  - id: cbc
    name: Center for Brain and Cognition
    department: Universitat Pompeu Fabra
  - id: ul
    name: Facultade de Letras
    department: Universidade de Lisboa
  - id: uam 
    name: Departamento de Psicología
    department: Universidad Autónoma de Madrid

csl: "../assets/apa7.csl"
bibliography: "../assets/references.bib"