---
title: Docker {{< fa brands docker >}}
---

1. Download and install Docker
2. Pull the [gongcastro/cognate-beginnings image](https://hub.docker.com/r/gongcastro/cognate-beginnings). Two ways of doing this:
    a) Using the Docker UI: go the the "Images" tab, click on "Search images to run", search for "gongcastro/cognate-beginnings", and click "Pull".
    b) Using the Docker CLI: open your console/terminal/command prompt, and run:
    ```bash 
    docker pull gongcastro/cognate-beginnings
    ```
3. Run the image in a Docker container. Two ways of doing this:
    a) Using the Docker UI: in the "Images" tab, look for the `gongcastro/cognate-beginnings` image and click "Run".
    b) Using the Docker CLI:
    ```bash 
    docker run --rm -ti -e ROOT=true -e PASSWORD=rstudio -p 8787:8787 --name rstudio gongcastro/cognate-beginnings:latest
    ```

4. Open [https://localhost:8787](https://localhost:8787) in your browser. Log in using `rstudio` as user, and `rstudio` as password. An RStudio session should open, with all files, code and dependencies installed and ready. To retrieve and explore a given object, run `targets::tar_load(target_name)`, where `target_name` is the name of the rarget you want to explore (e.g., `targets::tar_load(items)`).

> 💡 The RStudio session opened by Docker does not have root permissions (you will not be able to run `targets::tar_make()` to run the code from the R console). Instead, open the "Terminal" tab, and run `sudo Rscript -e "targets::tar_make()"`. The targets workflow should now be triggered.

> 💡 The targets workflow is run to completion before your Rstudio session is open in Docker. This means that even if you trigger `targets::tar_make()`, virtually all targets will be skipped, as they are completed. If you want to run a specific target, delete it first (or any other target it depends on), and the targets workflow will be run, now generating all deleted targets again. Be aware that this might take some time, especially when fitting the models anew.


