<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>manuscript</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="manuscript_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript_files/libs/quarto-html/quarto.js"></script>
<script src="manuscript_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="manuscript_files/libs/quarto-html/anchor.min.js"></script>
<link href="manuscript_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="sec-introduction" class="level1">
<h1>Introduction</h1>
<section id="word-acquisition-during-toddlerhood-the-effect-of-language-experience" class="level2">
<h2 class="anchored" data-anchor-id="word-acquisition-during-toddlerhood-the-effect-of-language-experience">Word acquisition during toddlerhood: the effect of language experience</h2>
<p>The foundations of word learning are in place early in age. Before the end of their first year of life infants start directing their gaze to some objects when hearing their labels, according to both experimental data <span class="citation" data-cites="jusczyk1995infants tincoff1999some bergelson2012months bergelson2015early">[@jusczyk1995infants; @tincoff1999some; @bergelson2012months; @bergelson2015early]</span> and parental vocabulary reports <span class="citation" data-cites="fenson2007macarthur">[e.g., @fenson2007macarthur]</span>. During the last half of their second year, new word forms are acquired at an increasingly fast rate <span class="citation" data-cites="goldfield1990early fenson1994variability mayor2011statistical bloom2002children bergelson2020comprehension">[@goldfield1990early; @fenson1994variability; @mayor2011statistical; @bloom2002children; @bergelson2020comprehension]</span>. These early stages of lexical acquisition are characterised by substantial variation across children. This is reflected, for instance, on the variability of the number of words they know <span class="citation" data-cites="fenson1994variability frank2021variability">[i.e. vocabulary size, @fenson1994variability; @frank2021variability]</span> or on the proportion of acquired words that fall into the category of nouns, as opposed to verbs, adjectives, or function words <span class="citation" data-cites="nelson1973structure">[e.g., @nelson1973structure, @bates1994developmental]</span>.</p>
<p>Despite this variability, children’s trajectories of vocabulary growth seem quite stable across languages. <span class="citation" data-cites="tardif2008baby">@tardif2008baby</span> collected data about the first ten words acquired by 10 to 16 month-old infants living in the United States, Hong Kong, and Beijing. Since birth, these infants had been learning English, Cantonese and Mandarin, respectively. The authors found a common pattern across the three groups: their first ten words referred to roughly the same concepts, namely relatives/caretakers (<em>daddy</em>, <em>mommy</em>), social routines (<em>bye</em>, <em>uh-oh</em>) or animals (<em>woof-woof</em>). These results were later extended by <span class="citation" data-cites="frank2021variability">@frank2021variability</span> to a wider diversity languages, also reporting that such cross-language commonalities are stronger at earlier stages of lexical acquisition, compared to later stages. Most of the literature on early word acquisition, however, has been conducted on monolingual children, and neglects the problem of how bilinguals–who represent a substantial proportion of the population in most societies–acquire words at early ages.</p>
<p>Previous findings point to bilingual toddlers knowing, on average, less words in each of their languages than their monolinguals peers, but also to both groups knowing a similar amount of words when the two languages are aggregated. For example, <span class="citation" data-cites="hoff2012dual">@hoff2012dual</span> found that English-Spanish bilingual toddlers in South Florida knew less words in English than monolinguals, who only learnt English. Both groups knew a similar total amount of words when both English and Spanish vocabularies were counted together, highlighting the importance of collecting data on both languages when assessing bilinguals’ communicative development. Other studies have provided converging evidence that bilinguals know a similar–or even larger–number of words than monolinguals, only when the languages are aggregated <span class="citation" data-cites="oller2002language pearson1994patterns pearson1993lexical patterson2004comparing patterson2004bilingual smithson2014bilingualism petitto2001bilingual gonzalez2020bilingual">[@oller2002language; @pearson1994patterns; @pearson1993lexical; @patterson2004comparing; @patterson2004bilingual; @smithson2014bilingualism; @petitto2001bilingual; @gonzalez2020bilingual]</span>. While these studies have mostly relied on samples of bilingual children learning two relatively distant languages, as it is the case of English and Spanish, it is unclear whether children learning typologically more similar languages also know less words in each of their languages than monolinguals. What role could linguistic distance play during early vocabulary growth?</p>
</section>
<section id="language-distance-as-a-mediator-of-bilingual-vocabulary-growth" class="level2">
<h2 class="anchored" data-anchor-id="language-distance-as-a-mediator-of-bilingual-vocabulary-growth">Language distance as a mediator of bilingual vocabulary growth</h2>
<p>For a given set of concepts, bilingual children may be exposed to two distinct sets of word-forms–one in each language. Depending on the linguistic distance between both languages, the two sets of words may overlap in varying degrees. Particularly, when both languages are typologically close, like Spanish and Catalan (both Roman languages), they are more likely to share a large amount of cognates (i.e., form-similar translation equivalents) than two typologically distant languages, like Spanish and English (one Romance, the other Germanic). For instance, in the presence of a door, a Spanish-Italian (or a Spanish-Catalan) bilingual might hear <em>puerta</em> and <em>porta</em> (cognates), whereas a Spanish-English bilingual might hear <em>puerta</em> and <em>door</em> (non-cognates). It could be the case that mapping two phonologically similar labels (cognates like <em>puerta</em>-<em>porta</em>) onto the same referent is easier than doing the same with two phonologically dissimilar labels (non-cognates, like <em>puerta</em> and <em>door</em>). If cognates are easier to acquire than non-cognates, bilinguals learning a pair of languages that share a high proportion of cognates should benefit more often from this facilitation effect than those learning a pair of languages with a lower proportion of cognates, and should therefore show larger vocabulary sizes.</p>
<p><span class="citation" data-cites="floccia2018introduction">@floccia2018introduction</span> provided evidence in line with this claim. The authors collected vocabulary data on word comprehension and production from 372 24-month-old bilingual toddlers living in the United Kingdom who were learning English and an additional language. The additional language was one a pool of 13 typologically diverse languages: Bengali, Cantonese Chinese, Dutch, French, German, Greek, Hindi/Urdu, Italian, Mandarin Chinese, Polish, Portuguese, Spanish and Welsh. The authors calculated the average phonological similarity between the words in each of these additional languages and their translation equivalents in English. Phonological similarity was measured by computing the Levenshtein distance between each cross-language pair of phonological transcriptions. The Levenshtein distance is a metric that computes the edit distance between two strings by counting the smallest number of insertions, deletions and substitutions one of the strings has to go through to become identical to the other <span class="citation" data-cites="levenshtein1966binary">[@levenshtein1966binary]</span>. The resulting scores were then divided by the length of the longest string to bound the similarity scores between 0 and 1, and then entered this variable as a predictor as they modelled participants’ vocabulary sizes. Among other findings, the authors reported an increase in productive vocabulary size in the additional language associated with an increase in the average phonological similarity between the translation equivalents of each language pair. For example, English-Dutch bilinguals (22.14% phonological similarity), were able to produce more Dutch words than English-Mandarin bilinguals (1.97% phonological similarity) were able to produce in Mandarin.</p>
</section>
<section id="lexical-non-selectiviy-as-a-candidate-acount-the-role-of-parallel-activation" class="level2">
<h2 class="anchored" data-anchor-id="lexical-non-selectiviy-as-a-candidate-acount-the-role-of-parallel-activation">Lexical non-selectiviy as a candidate acount: the role of parallel activation</h2>
<p>Floccia et al.&nbsp;pointed to <em>parallel activation</em> as the main phenomenon underpinning their results. The parallel activation hypothesis suggests that bilinguals activate both languages simultaneously during speech production or comprehension, and that this phenomenon is the result of the activation of lexical representations in both languages, even when only one is in use during production <span class="citation" data-cites="costa2000cognate hoshino2008cognate">[@costa2000cognate; @hoshino2008cognate]</span> or comprehension <span class="citation" data-cites="spivey1999cross thierry2007brain">[@spivey1999cross; @thierry2007brain]</span>. One of the clearest examples of parallel activation was provided by <span class="citation" data-cites="costa2000cognate">@costa2000cognate</span>. In this study, Catalan-Spanish monolingual and bilingual adults were asked to name pictures of common objects in Spanish. In half of the trials, the object labels were cognates in Spanish and Catalan (<em>árbol</em>-<em>arbre</em>, translations of <em>tree</em>), whereas in the other half of the trials labels were non-cognates (<em>mesa</em>-<em>taula</em>, translations of <em>table</em>). Bilinguals named cognate pictures faster than non-cognate pictures, even after adjusting for the lexical frequency of the items. Importantly, Spanish monolinguals–unfamiliar with the Catalan translations of the Spanish words they uttered–did not show this effect. These results suggest that bilinguals’ Catalan phonology was activated during the production of Spanish words, facilitating the naming of cognate pictures. Several subsequent studies have also provided similar evidence in comprehension in children <span class="citation" data-cites="von2012language poulin2013lexical">[e.g., @von2012language; @poulin2013lexical]</span>. Parallel activation is therefore a plausible explanation for Floccia et al.’s results: cognateness increases the amount of cross-language activation, facilitating word acquisition, and ultimately leading to children learning language pairs with a larger proportion of cognates are predicted to show larger vocabulary sizes. This account is is line with previous studies suggesting that the acquisition of new words is facilitated by their phonological or semantic similarity with other words, already acquired or not <span class="citation" data-cites="hills2009longitudinal fourtassi2020growth laing2022phonological jones2019children">[e.g., @hills2009longitudinal; @fourtassi2020growth; @laing2022phonological; @jones2019children]</span>. Importantly, bilinguals seem to be more likely to acquire words for which their translation equivalent has been already learnt in the other language, suggesting that semantic similarity also facilitates word acquisition across languages <span class="citation" data-cites="bilson2015semantic">[@bilson2015semantic]</span>.</p>
<p>If phonological similarity also plays a cross-language facilitation role during word acquisition, cognate translation equivalents–which share both semantic and phonological similarity–should be acquired earlier that non-cognate translation equivalents–which share semantic similarity, but not phonological similarity. Evidence supporting and earlier age of acquisition for cognates is scarce. <span class="citation" data-cites="bosch2014first">@bosch2014first</span> used vocabulary parental reports (152 lexical items) from 48 Catalan-Spanish bilinguals aged 18 months, and found that cognates represented a larger proportion of participant’s vocabulary than non-cognates. <span class="citation" data-cites="schelletter2002effect">@schelletter2002effect</span> reported a longitudinal single case of one English-German bilingual who produced cognates earlier than non-cognates, on average. The low sample size in these two studies makes it challenging to draw strong conclusions about the effect of cognateness on vocabulary growth. On the other hand, Floccia et al.’s estimates are statically more reliable given their (much larger) sample size, but their study was not aimed at testing the effect of cognateness on age of acquisition directly. In their discussion the authors state the following (pp.&nbsp;70):</p>
<blockquote class="blockquote">
<p>“This finding also provides support to the proposal that the cognate advantage is due to cognates being acquired before non-cognates in early childhood (Costa et al., 2016), leading to an ease of processing later in life.”</p>
</blockquote>
<p>We identify two main reasons why an earlier age of acquisition for cognates than for non-cognates is an unwarranted conclusion from Floccia et al.’s results. First, the response variable used was the proportion of words each participant understood and/or produced (i.e., vocabulary size), from the list of lexical items in the vocabulary checklists. By aggregating the responses from all items into a single datum per child, information about the acquisition status of cognates vs.&nbsp;non-cognates was lost. Second, all participants were aged ~24 months, meaning that even if the unaggregated responses to individual items were included as response variable, the possible effect of cognateness could only be interpreted as an increase or decrease in the likelihood of participants at such age to have acquired each item, and not as an increase or decrease in the age of acquisition of such item.</p>
<p>More recently, <span class="citation" data-cites="mitchell2022cognates">@mitchell2022cognates</span> addressed this issue overcoming some of these pitfalls. Using a larger, longitudinal sample of 47 16-to-30 month-old French-English bilinguals living in Canada, the authors collected data on expressive vocabulary data in both languages. They created two lists of translation equivalents: one made of 131 cognates, and one made of 406 non-cognates. The proportion of translation equivalents that children were reportedly able to produce was higher in the cognate lists than in the non-cognate list across ages, even when both lists were matched by semantic category (furniture, animals, food were similarity represented in both lists) and age of acquisition norms (an index of word difficulty). These findings shed some light on the ongoing exploration of why (if at all) bilinguals’ vocabulary size grows faster when both languages are phonologically more similar: word-forms sharing more phonemes with their translation equivalents (i.e., cognates) seem to be acquired faster.</p>
</section>
<section id="two-competing-mechanisms-for-a-cognate-facilitation-during-word-acquisition" class="level2">
<h2 class="anchored" data-anchor-id="two-competing-mechanisms-for-a-cognate-facilitation-during-word-acquisition">Two competing mechanisms for a cognate facilitation during word acquisition</h2>
<p>The facilitative effect of cognateness on word acquisition can be explained by at least two arguably incompatible mechanisms. On the one hand, and in line with <span class="citation" data-cites="mitchell2022cognates">@mitchell2022cognates</span>, cognateness might operate at early stages of word acquisition, before stable representations of any of the word-forms of the translation equivalent have been formed. In this scenario, recognising any of the two word-forms as familiar might lead to the activation of its (cognate) translation in the other language via their phonological similarity. Given that both word-forms are likely to be heard in the presence of the same referent, the association between each form and such reference could be facilitated by the exposure to either of them.</p>
<p>For instance, hearing <em>flower</em> in English might activate <em>floeur</em> in French, and <em>vice versa</em>. Repeated exposure to the English or the French words, and therefore to similar -sounding words in the presence of eventually leads to an earlier acquisition for both of them, as compared to non-cognate translation equivalents like <em>cow</em> and <em>vache</em>, which do not activate each other via phonological similarity. If this is the case, then cognateness should increase the probability of acquisition of the word-forms in both languages equally.</p>
<p>Another possibility is that cognateness plays a role in the acquisition of a translation pair only when at least one of the word-forms has been acquired. This account departs from the premise that phonological similarity operates at the lexical level to facilitate word learning across languages: if the child has still not formed a lexical representation with sufficient phonological detail for one of the word forms, the acquisition of its translation in the other language cannot be facilitated by cognateness. This implies that, if cognateness facilitates the acquisition of a word form, it can only do so after the child has acquired one of the word forms of the translation pair. Given that children are more likely to acquire words from languages to which they are exposed more often <span class="citation" data-cites="david2008individual cattani2014much thordardottir2006bilingual">[@david2008individual; @cattani2014much; @thordardottir2006bilingual]</span>, the acquisition of words in the language of lower exposure should, on average, be more susceptible to the effect of cognateness.</p>
<p>In line with this second hypothesis, the size of the effect of linguistic similarity on vocabulary size that Floccia et al.&nbsp;reported was larger in the additional language (language of lower exposure) vocabulary than in English vocabulary (language of higher exposure. Most participants in their sample were English-dominant, meaning that their relative amount of exposure to English was larger than in the additional language. Therefore, participants may have, on average, learnt the English word-form of translation equivalents earlier than the word-form in the additional language. If this is the case, then the acquisition of English words by English-dominant participants would rarely benefit from their cognate status (the other word-form is not available yet), while the acquisition of words in the additional language would benefit from their phonological similarity with the (available) English form.</p>
</section>
<section id="the-present-study" class="level2">
<h2 class="anchored" data-anchor-id="the-present-study">The present study</h2>
<p>In this study, we investigated the role of cognateness on the acquisition of translation equivalents, and if such effect is conditional to the amount of time the child is exposed to the corresponding language of each member of the translation pair. Using an online vocabulary checklist–designed specifically for this study–we collected data from a sample of children aged 12 to 31 months learning Catalan and/or Spanish, with varying degrees of exposure to each language. We then adopted an Bayesian item response theory (<em>IRT</em>) approach to model the probability of participants being reported by their parents to understand or understand <em>and</em> say each word in the checklist, conditional to its cognate status in Catalan and Spanish and participants’ degree of exposure to the corresponding language, while adjusting for other indices of word difficulty–lexical frequency <span class="citation" data-cites="goodman2008does">[@goodman2008does]</span> and length (phonemes)– and participant skill–age <span class="citation" data-cites="kachergis2022toward">[see @kachergis2022toward for a similar approach]</span>.</p>
</section>
</section>
<section id="sec-methods" class="level1">
<h1>Methods</h1>
<section id="sec-participants" class="level2">
<h2 class="anchored" data-anchor-id="sec-participants">Participants</h2>
<p>We collected data from 384 children from the Metropolitan Area of Barcelona between 28th October, 2019 and 31th October, 2022. All families gave informed consent before participating and this study was approved by the Comitè d’Ètica de la Investigació amb Medicaments (CEIm) from Hospital del Mar (Barcelona, Spain), code XXXXXXXXX. Families from the participant database of the Laboratori de Recerca en Infància of the Universitat Pompeu Fabra were contacted by e-mail or phone if their child were aged between 12 and 31 months, and had not been reported to be exposed more than 10% of the time to a language other than Spanish or Catalan. Upon consent, families were sent a link to the questionnaire via e-mail, which they filled from a computer, laptop, or mobile device in a browser within the two week following the invitation to participate. <a href="#tbl-participants-lp">Table&nbsp;1</a> summarises the distribution of participants across ages and degrees of exposure (DoE) to Catalan.</p>
<div id="tbl-participants-lp" class="cell tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p>Table&nbsp;1: Participant sample size by age and degree of exposure to Catalan.</p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-participants-lp-1" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-participants-lp" style="flex-basis: 100.0%;justify-content: center;">

<div id="yxjtusldxl" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#yxjtusldxl) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#yxjtusldxl) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#yxjtusldxl) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#yxjtusldxl) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#yxjtusldxl) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#yxjtusldxl) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#yxjtusldxl) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#yxjtusldxl) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#yxjtusldxl) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#yxjtusldxl) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#yxjtusldxl) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#yxjtusldxl) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#yxjtusldxl) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#yxjtusldxl) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#yxjtusldxl) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#yxjtusldxl) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#yxjtusldxl) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#yxjtusldxl) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#yxjtusldxl) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#yxjtusldxl) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#yxjtusldxl) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#yxjtusldxl) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#yxjtusldxl) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#yxjtusldxl) .gt_left {
  text-align: left;
}

:where(#yxjtusldxl) .gt_center {
  text-align: center;
}

:where(#yxjtusldxl) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#yxjtusldxl) .gt_font_normal {
  font-weight: normal;
}

:where(#yxjtusldxl) .gt_font_bold {
  font-weight: bold;
}

:where(#yxjtusldxl) .gt_font_italic {
  font-style: italic;
}

:where(#yxjtusldxl) .gt_super {
  font-size: 65%;
}

:where(#yxjtusldxl) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#yxjtusldxl) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#yxjtusldxl) .gt_indent_1 {
  text-indent: 5px;
}

:where(#yxjtusldxl) .gt_indent_2 {
  text-indent: 10px;
}

:where(#yxjtusldxl) .gt_indent_3 {
  text-indent: 15px;
}

:where(#yxjtusldxl) .gt_indent_4 {
  text-indent: 20px;
}

:where(#yxjtusldxl) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table"><caption>(a) Information about DoE was provided by families before filling the questionnaire. A 100% indicated that the participant was exclusively exposed to Catalan, and never to Spanish. A 0% indicates that the participant was not exposed to Catalan ever, and rather most of the time to Spanish. A 50% indicates that the participant was exposed to Catalan and Spanish approximately half of the time each. The 100%, 0%, and 50% would be traditionaly classified as Catalan monolingual, Spanish monolingual, and Catalan-Spanish bilingual, respectively. For illustration purposes this table, DoEs were binned into 25%-wide bins, and ages (in months) binned into 4 month-wide bins. Hyphens indicate that no participants from that specific combination of age and DoE filled the questionnaire. </caption>
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" style="text-align: left;" scope="col" id="DoE Catalan<sup class=&quot;gt_footnote_marks&quot;>1</sup>">DoE Catalan<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="6" scope="colgroup" id="Age (months)">
        <span class="gt_column_spanner">Age (months)</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="[10,14]">[10,14]</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="(14,18]">(14,18]</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="(18,22]">(18,22]</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="(22,26]">(22,26]</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="(26,30]">(26,30]</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="(30,34]">(30,34]</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_left gt_stub"></th>
<td headers="stub_1_1 doe_catalan" class="gt_row gt_right" style="text-align: left;">75-100%</td>
<td headers="stub_1_1 [10,14]" class="gt_row gt_right">17</td>
<td headers="stub_1_1 (14,18]" class="gt_row gt_right">25</td>
<td headers="stub_1_1 (18,22]" class="gt_row gt_right">37</td>
<td headers="stub_1_1 (22,26]" class="gt_row gt_right">39</td>
<td headers="stub_1_1 (26,30]" class="gt_row gt_right">22</td>
<td headers="stub_1_1 (30,34]" class="gt_row gt_right">6</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_left gt_stub"></th>
<td headers="stub_1_2 doe_catalan" class="gt_row gt_right" style="text-align: left;">50-75%</td>
<td headers="stub_1_2 [10,14]" class="gt_row gt_right">8</td>
<td headers="stub_1_2 (14,18]" class="gt_row gt_right">13</td>
<td headers="stub_1_2 (18,22]" class="gt_row gt_right">27</td>
<td headers="stub_1_2 (22,26]" class="gt_row gt_right">39</td>
<td headers="stub_1_2 (26,30]" class="gt_row gt_right">22</td>
<td headers="stub_1_2 (30,34]" class="gt_row gt_right">2</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_left gt_stub"></th>
<td headers="stub_1_3 doe_catalan" class="gt_row gt_right" style="text-align: left;">25-50%</td>
<td headers="stub_1_3 [10,14]" class="gt_row gt_right">10</td>
<td headers="stub_1_3 (14,18]" class="gt_row gt_right">16</td>
<td headers="stub_1_3 (18,22]" class="gt_row gt_right">48</td>
<td headers="stub_1_3 (22,26]" class="gt_row gt_right">29</td>
<td headers="stub_1_3 (26,30]" class="gt_row gt_right">24</td>
<td headers="stub_1_3 (30,34]" class="gt_row gt_right">1</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_left gt_stub"></th>
<td headers="stub_1_4 doe_catalan" class="gt_row gt_right" style="text-align: left;">0-25%</td>
<td headers="stub_1_4 [10,14]" class="gt_row gt_right">6</td>
<td headers="stub_1_4 (14,18]" class="gt_row gt_right">12</td>
<td headers="stub_1_4 (18,22]" class="gt_row gt_right">21</td>
<td headers="stub_1_4 (22,26]" class="gt_row gt_right">19</td>
<td headers="stub_1_4 (26,30]" class="gt_row gt_right">9</td>
<td headers="stub_1_4 (30,34]" class="gt_row gt_right">1</td></tr>
    <tr><th id="grand_summary_stub_1" scope="row" class="gt_row gt_left gt_stub gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row">Total</th>
<td headers="grand_summary_stub_1 doe_catalan" class="gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row">—</td>
<td headers="grand_summary_stub_1 [10,14]" class="gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row">41</td>
<td headers="grand_summary_stub_1 (14,18]" class="gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row">66</td>
<td headers="grand_summary_stub_1 (18,22]" class="gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row">133</td>
<td headers="grand_summary_stub_1 (22,26]" class="gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row">126</td>
<td headers="grand_summary_stub_1 (26,30]" class="gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row">77</td>
<td headers="grand_summary_stub_1 (30,34]" class="gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row">10</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="8"><sup class="gt_footnote_marks">1</sup> This proportion is complementary to the degree of exposure to Spanish, with the exception of those participants who were also exposed to a third language up to 10% of the time</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
</div>
<p>We used the highest educational attainment of parents or caretakers as a proxy of participants’ socio-economic status (SES), which families self-reported in the questionnaire by filling two items asking for the educational attainment of each parent or caretaker, with the following available options: <em>No education</em>, <em>Primary</em>, <em>Secondary</em>, <em>Complementary</em>, <em>Vocational</em>, and <em>University</em>, in line with the current educational system in Spain. Most families reported university studies (366, 0.953125), followed by families were the highest educational attainment were vocational studies (66, 17%), complementary studies (6, 2%), secondary education (8, 2%, 0%), no formal education (2, 1% and primary education (1, &lt;1%).</p>
</section>
<section id="sec-questionnaire" class="level2">
<h2 class="anchored" data-anchor-id="sec-questionnaire">Questionnaire</h2>
<p>To collect vocabulary data from participants, we created an <em>ad hoc</em> questionnaire, MultiLex <span class="citation" data-cites="multilex">[@multilex]</span>. This questionnaire was inspired in the MacArthur-Bates Communicative Development Inventory <span class="citation" data-cites="fenson2007macarthur">[@fenson2007macarthur]</span> and its adaptations to other languages, and was implemented on-line using the formR platform <span class="citation" data-cites="arslan2020formr">[@arslan2020formr]</span>. This questionnaire is structured in three blocks: a (1) language questionnaire, a (2) demographic survey, and a (3) Catalan and a Spanish vocabulary checklists. Vocabulary checklists followed a similar structure as the Oxford Communicative Developmental Inventory <span class="citation" data-cites="hamilton2000infant">[@hamilton2000infant]</span> and consisted in two lists of words: one in Catalan and one in Spanish. The Catalan inventory contained 793 items and the Spanish inventory contained 797. Items in one language were translation equivalents of the items in the other language (e.g., whenever <em>gos</em> [dog] was included in the Catalan inventory, the word <em>perro</em> was included in the Spanish inventory), roughly following a one-to-one mapping. In case two translation equivalents were possible for a given word, both were included as separate items (e.g., Catalan <em>acabar</em> [<em>to finish</em>] and Spanish <em>acabar</em> and <em>terminar</em>), or merged them into a single item (e.g., Spanish <em>mono</em> [<em>monkey</em>] and Catalan <em>mono/mico</em>). We included items from a diverse sample of 26 semantic/functional categories.</p>
<p>For each word in the vocabulary checklists, we asked parents to report whether their child was able to understand it, understand <em>and</em> say it, or did not understand or say it (checked out by default). Some families filled a long version of the vocabulary checklists (797 translation equivalents; 793 items in Catalan, 797 items in Spanish), while others filled a shorter version (~400 translation equivalents, ~400 items in Catalan, ~400 items in Spanish). These last families were randomly allocated into one of four different subsets of the complete list of items. These lists were designed so that each contained a representative sub-sample of the items from the complete list. Semantic/functional categories with less than 16 items–thus resulting in less than four items after dividing it in four lists–were not divided in the short version of the questionnaire: all of their items were included in the four lists. Another subset of items that were part of the trial lists of some experiments in the lab were also included in all versions. For the analyses in the present study, we considered responses to words corresponding to nouns, verbs, and adjectives <span class="citation" data-cites="fourtassi2020growth">[@fourtassi2020growth]</span>. We excluded multi-word items (e.g., <em>barrita de cereales</em> [cereal bar]) and items that included more than one word-form (e.g., <em>mono/mico</em>).</p>
</section>
<section id="variables-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="variables-of-interest">Variables of interest</h2>
<p>We extracted four variables of interest for each word-form. (1) Word lexical frequency (<span class="math inline">\(Frequency\)</span>): lexical frequency of the word in its corresponding language, expressed as Zipf scores <span class="citation" data-cites="van2014subtlex zipf1949human">[@van2014subtlex; @zipf1949human]</span>. This variable ranges from 0 to 7, and follows and approximates a normal distribution, with most values in a corpus ranging from 3 to 5 points. Lexical frequencies were extracted from an adult subtitle-based database: SUBTLEX-CAT <span class="citation" data-cites="boada2020subtlex">[@boada2020subtlex]</span> for Catalan words and SUBTLEX-ESP <span class="citation" data-cites="cuetos2012subtlex">[@cuetos2012subtlex]</span> for Spanish words. Using child-based estimates of lexical frequency like CHILDES was not possible due to the low number of Catalan participants and tokens in the available corpora. (2) Word length (<span class="math inline">\(Phonemes\)</span>): number of phonemes in the phonological transcription of the word-form in International Phonological association format. (3) Phonological similarity (<span class="math inline">\(Levenshtein\)</span>): normalised Levenshtein similarity between the word-form and its translation in the other language <span class="citation" data-cites="levenshtein1966binary">[@levenshtein1966binary]</span>. This score is calculated by first calculating the Levenshtein distance between the two transcriptions (number of insertions, deletions or replacements needed for the shortest transcription to become identical to the longer transcription), then dividing the resulting value by the length of the longest transcription, and finally subtracting this value from 1. This results in a proportion that indicates how much the two phonological transcriptions of the translation equivalent are similar to each other, ranging from 0% (no similarity at all) to 100% (both transcriptions are identical) <span class="citation" data-cites="floccia2018introduction fourtassi2020growth laing2022phonological">[see @floccia2018introduction; @fourtassi2020growth; @laing2022phonological for similar approaches]</span>. (4) Participant age: number of months elapsed between participants’ birth date and questionnaire completion. Finally, (5) participant degree of exposure to the words’ language (<span class="math inline">\(DoE\)</span>): percentage of exposure to the language the word belonged to. For example, for a participant with 90% exposure to Catalan, and 10% to Spanish, the DoE of the Catalan word <em>taula</em> would be 90%, and the DoE for the Spanish word <em>mesa</em> would be 10%. <a href="#tbl-item-summary">Table&nbsp;2</a> shows a summary of the distribution of the word-level predictors across languages in and questionnaire versions.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-item-summary" class="anchored">

<div id="ibvjfwestk" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#ibvjfwestk) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#ibvjfwestk) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#ibvjfwestk) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#ibvjfwestk) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#ibvjfwestk) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#ibvjfwestk) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#ibvjfwestk) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#ibvjfwestk) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#ibvjfwestk) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#ibvjfwestk) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#ibvjfwestk) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#ibvjfwestk) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#ibvjfwestk) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#ibvjfwestk) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ibvjfwestk) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#ibvjfwestk) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#ibvjfwestk) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ibvjfwestk) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#ibvjfwestk) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ibvjfwestk) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#ibvjfwestk) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ibvjfwestk) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#ibvjfwestk) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ibvjfwestk) .gt_left {
  text-align: left;
}

:where(#ibvjfwestk) .gt_center {
  text-align: center;
}

:where(#ibvjfwestk) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#ibvjfwestk) .gt_font_normal {
  font-weight: normal;
}

:where(#ibvjfwestk) .gt_font_bold {
  font-weight: bold;
}

:where(#ibvjfwestk) .gt_font_italic {
  font-style: italic;
}

:where(#ibvjfwestk) .gt_super {
  font-size: 65%;
}

:where(#ibvjfwestk) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#ibvjfwestk) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#ibvjfwestk) .gt_indent_1 {
  text-indent: 5px;
}

:where(#ibvjfwestk) .gt_indent_2 {
  text-indent: 10px;
}

:where(#ibvjfwestk) .gt_indent_3 {
  text-indent: 15px;
}

:where(#ibvjfwestk) .gt_indent_4 {
  text-indent: 20px;
}

:where(#ibvjfwestk) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table"><caption>Table&nbsp;2:  Lexical properties of the word-forms and translation pairs included in the vocabulary checklist and our analyses. We report the number of items, mean, standard deviation (SD), and range of the lexical frequency (epxressed in Zipf scores), length (number of phonemes) of the word forms, and the phonological similarity (normalised Levenshtein similarity) with their translation equivalent. Statistics are reported separately for Catalan and Spanish, and for the different vocabulary checklists that participants were allocated to (A, B, C, D). </caption>
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" style="font-style: italic;" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" style="font-style: italic;" scope="col" id="<em>N</em>"><em>N</em></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" style="font-weight: bold;" scope="colgroup" id="Frequency (Zipf)">
        <span class="gt_column_spanner">Frequency (Zipf)</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" style="font-weight: bold;" scope="colgroup" id="Length (Phonemes)">
        <span class="gt_column_spanner">Length (Phonemes)</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" style="font-weight: bold;" scope="colgroup" id="Phon. similarity (Levenshtein)">
        <span class="gt_column_spanner">Phon. similarity (Levenshtein)</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-style: italic;" scope="col" id="Mean">Mean</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-style: italic;" scope="col" id="<em>SD</em>"><em>SD</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-style: italic;" scope="col" id="Range">Range</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-style: italic;" scope="col" id="Mean">Mean</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-style: italic;" scope="col" id="<em>SD</em>"><em>SD</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-style: italic;" scope="col" id="Range">Range</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-style: italic;" scope="col" id="Mean">Mean</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-style: italic;" scope="col" id="<em>SD</em>"><em>SD</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-style: italic;" scope="col" id="Range">Range</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <th colspan="11" class="gt_group_heading" scope="colgroup" id="Catalan">Catalan</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Catalan  list" class="gt_row gt_left">A</td>
<td headers="Catalan  n" class="gt_row gt_right">167</td>
<td headers="Catalan  freq_zipf_mean" class="gt_row gt_right">6.04</td>
<td headers="Catalan  freq_zipf_sd" class="gt_row gt_right">0.19</td>
<td headers="Catalan  freq_zipf_min" class="gt_row gt_right">5.16–6.53</td>
<td headers="Catalan  n_phon_mean" class="gt_row gt_right">5.17</td>
<td headers="Catalan  n_phon_sd" class="gt_row gt_right">1.57</td>
<td headers="Catalan  n_phon_min" class="gt_row gt_right">2–11</td>
<td headers="Catalan  lv_mean" class="gt_row gt_right">37.39%</td>
<td headers="Catalan  lv_sd" class="gt_row gt_right">26.44%</td>
<td headers="Catalan  lv_min" class="gt_row gt_right">0.00%–100.00%</td></tr>
    <tr><td headers="Catalan  list" class="gt_row gt_left">B</td>
<td headers="Catalan  n" class="gt_row gt_right">150</td>
<td headers="Catalan  freq_zipf_mean" class="gt_row gt_right">6.02</td>
<td headers="Catalan  freq_zipf_sd" class="gt_row gt_right">0.19</td>
<td headers="Catalan  freq_zipf_min" class="gt_row gt_right">5.16–6.55</td>
<td headers="Catalan  n_phon_mean" class="gt_row gt_right">5.05</td>
<td headers="Catalan  n_phon_sd" class="gt_row gt_right">1.62</td>
<td headers="Catalan  n_phon_min" class="gt_row gt_right">2–10</td>
<td headers="Catalan  lv_mean" class="gt_row gt_right">34.58%</td>
<td headers="Catalan  lv_sd" class="gt_row gt_right">25.18%</td>
<td headers="Catalan  lv_min" class="gt_row gt_right">0.00%–88.89%</td></tr>
    <tr><td headers="Catalan  list" class="gt_row gt_left">C</td>
<td headers="Catalan  n" class="gt_row gt_right">149</td>
<td headers="Catalan  freq_zipf_mean" class="gt_row gt_right">6.03</td>
<td headers="Catalan  freq_zipf_sd" class="gt_row gt_right">0.18</td>
<td headers="Catalan  freq_zipf_min" class="gt_row gt_right">5.16–6.55</td>
<td headers="Catalan  n_phon_mean" class="gt_row gt_right">5.17</td>
<td headers="Catalan  n_phon_sd" class="gt_row gt_right">1.59</td>
<td headers="Catalan  n_phon_min" class="gt_row gt_right">2–9</td>
<td headers="Catalan  lv_mean" class="gt_row gt_right">36.86%</td>
<td headers="Catalan  lv_sd" class="gt_row gt_right">26.94%</td>
<td headers="Catalan  lv_min" class="gt_row gt_right">0.00%–100.00%</td></tr>
    <tr><td headers="Catalan  list" class="gt_row gt_left">D</td>
<td headers="Catalan  n" class="gt_row gt_right">156</td>
<td headers="Catalan  freq_zipf_mean" class="gt_row gt_right">6.02</td>
<td headers="Catalan  freq_zipf_sd" class="gt_row gt_right">0.18</td>
<td headers="Catalan  freq_zipf_min" class="gt_row gt_right">5.16–6.49</td>
<td headers="Catalan  n_phon_mean" class="gt_row gt_right">5.13</td>
<td headers="Catalan  n_phon_sd" class="gt_row gt_right">1.55</td>
<td headers="Catalan  n_phon_min" class="gt_row gt_right">2–10</td>
<td headers="Catalan  lv_mean" class="gt_row gt_right">36.00%</td>
<td headers="Catalan  lv_sd" class="gt_row gt_right">26.72%</td>
<td headers="Catalan  lv_min" class="gt_row gt_right">0.00%–85.71%</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="11" class="gt_group_heading" scope="colgroup" id="Spanish">Spanish</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Spanish  list" class="gt_row gt_left">A</td>
<td headers="Spanish  n" class="gt_row gt_right">169</td>
<td headers="Spanish  freq_zipf_mean" class="gt_row gt_right">6.03</td>
<td headers="Spanish  freq_zipf_sd" class="gt_row gt_right">0.19</td>
<td headers="Spanish  freq_zipf_min" class="gt_row gt_right">5.16–6.53</td>
<td headers="Spanish  n_phon_mean" class="gt_row gt_right">5.47</td>
<td headers="Spanish  n_phon_sd" class="gt_row gt_right">1.41</td>
<td headers="Spanish  n_phon_min" class="gt_row gt_right">3–10</td>
<td headers="Spanish  lv_mean" class="gt_row gt_right">37.39%</td>
<td headers="Spanish  lv_sd" class="gt_row gt_right">26.37%</td>
<td headers="Spanish  lv_min" class="gt_row gt_right">0.00%–100.00%</td></tr>
    <tr><td headers="Spanish  list" class="gt_row gt_left">B</td>
<td headers="Spanish  n" class="gt_row gt_right">157</td>
<td headers="Spanish  freq_zipf_mean" class="gt_row gt_right">6.03</td>
<td headers="Spanish  freq_zipf_sd" class="gt_row gt_right">0.19</td>
<td headers="Spanish  freq_zipf_min" class="gt_row gt_right">5.16–6.55</td>
<td headers="Spanish  n_phon_mean" class="gt_row gt_right">5.50</td>
<td headers="Spanish  n_phon_sd" class="gt_row gt_right">1.58</td>
<td headers="Spanish  n_phon_min" class="gt_row gt_right">3–10</td>
<td headers="Spanish  lv_mean" class="gt_row gt_right">35.06%</td>
<td headers="Spanish  lv_sd" class="gt_row gt_right">25.54%</td>
<td headers="Spanish  lv_min" class="gt_row gt_right">0.00%–100.00%</td></tr>
    <tr><td headers="Spanish  list" class="gt_row gt_left">C</td>
<td headers="Spanish  n" class="gt_row gt_right">158</td>
<td headers="Spanish  freq_zipf_mean" class="gt_row gt_right">6.03</td>
<td headers="Spanish  freq_zipf_sd" class="gt_row gt_right">0.19</td>
<td headers="Spanish  freq_zipf_min" class="gt_row gt_right">5.16–6.55</td>
<td headers="Spanish  n_phon_mean" class="gt_row gt_right">5.53</td>
<td headers="Spanish  n_phon_sd" class="gt_row gt_right">1.56</td>
<td headers="Spanish  n_phon_min" class="gt_row gt_right">3–10</td>
<td headers="Spanish  lv_mean" class="gt_row gt_right">37.34%</td>
<td headers="Spanish  lv_sd" class="gt_row gt_right">27.04%</td>
<td headers="Spanish  lv_min" class="gt_row gt_right">0.00%–100.00%</td></tr>
    <tr><td headers="Spanish  list" class="gt_row gt_left">D</td>
<td headers="Spanish  n" class="gt_row gt_right">165</td>
<td headers="Spanish  freq_zipf_mean" class="gt_row gt_right">6.03</td>
<td headers="Spanish  freq_zipf_sd" class="gt_row gt_right">0.18</td>
<td headers="Spanish  freq_zipf_min" class="gt_row gt_right">5.16–6.53</td>
<td headers="Spanish  n_phon_mean" class="gt_row gt_right">5.52</td>
<td headers="Spanish  n_phon_sd" class="gt_row gt_right">1.53</td>
<td headers="Spanish  n_phon_min" class="gt_row gt_right">3–10</td>
<td headers="Spanish  lv_mean" class="gt_row gt_right">36.53%</td>
<td headers="Spanish  lv_sd" class="gt_row gt_right">26.85%</td>
<td headers="Spanish  lv_min" class="gt_row gt_right">0.00%–100.00%</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
</section>
<section id="sec-analysis" class="level2">
<h2 class="anchored" data-anchor-id="sec-analysis">Data analysis</h2>
<p>We gathered 138,488 observations, with each observation corresponding to a single response of one participant to a given item in the questionnaire). These observations correspond to 367 distinct participants (of which 314 participated once, 41 twice, 8 three times, and 4 four times), responding to 603 distinct items (299 in Catalan, 304 in Spanish, 304 translation equivalents). Translation equivalents (TEs) received a median of 232 responses (<em>Min</em> = 106, <em>Max</em> = 872), both languages summed together.</p>
<p>We modelled the probability of answering each response category (<em>No</em> &lt; <em>Understands</em> &lt; <em>Understands and Says</em>) using a Bayesian, mixed-effects ordinal regression model (4 sampling chains with 500 iterations each). This model allowed us to estimate both item and participant word-acquisition trajectories, as a function of different fixed effects from <span class="math inline">\(Age\)</span>, <span class="math inline">\(Frequency\)</span>, <span class="math inline">\(Phonemes\)</span>, <span class="math inline">\(DoE\)</span>, and <span class="math inline">\(Levenshtein\)</span>. We also included participant and item random intercepts and slopes when appropriate <span class="citation" data-cites="barr2013random">[@barr2013random]</span> <a href="#sec-appendix-words">see&nbsp;6.1</a>. We compared a baseline model <span class="math inline">\(\mathcal{M}_{0}\)</span>, which only included the intercept, <span class="math inline">\(Age\)</span>, <span class="math inline">\(Frequency\)</span>, <span class="math inline">\(Phonemes\)</span>, and <span class="math inline">\(DoE\)</span> as predictors, with increasingly more complex models, introducing predictors in the following order: <span class="math inline">\(Age \times DoE\)</span> (<span class="math inline">\(\mathcal{M}_{1}\)</span>), <span class="math inline">\(Levenshtein\)</span> (<span class="math inline">\(\mathcal{M}_{2}\)</span>), <span class="math inline">\(DoE \times Levenshtein\)</span> (<span class="math inline">\(\mathcal{M}_{3}\)</span>), and finally <span class="math inline">\(Age \times Levenshtein\)</span> and <span class="math inline">\(Age \times DoE \times Levenshtein\)</span> (<span class="math inline">\(\mathcal{M}_{4}\)</span>). We compared the predictive performance of the models using Bayesian leave-one-out cross-validation <span class="citation" data-cites="vehtari2017practical">[LOO, @vehtari2017practical]</span><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, and selected for interpretation the one showing the best performance.</p>
<p>We assessed the practical relevance of the estimated regression coefficients of the selected model by specifying a region of practical equivalence <span class="citation" data-cites="kruschke2018bayesian">[*ROPE*, @kruschke2018bayesian]</span> from -0.1 to +0.1 <a href="#sec-appendix-rope">see&nbsp;6.3</a>. This region indicates the range of values that we considered as equivalent to zero. The degree of overlap between the posterior distribution of a regression coefficient with the <em>ROPE</em> can be interpreted as support for the true parameter of the coefficient being zero. In the results section, we report the 95% highest density interval (<em>HDI</em>) of the posterior distribution of each regression coefficient. This is interval contains the true value of this coefficient with 95% probability, given our data. We also report the proportion of posterior samples in the 95% <em>HDI</em> that overlap with the <em>ROPE</em>, which indicates the probability that the true value of the regression coefficient falls into the <em>ROPE</em>, and should therefore be considered equivalent to zero<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p>Data processing and visualisation was done in R <span class="citation" data-cites="R-base">[@R-base]</span> using the <code>tidyverse</code> family of packages <span class="citation" data-cites="R-tidyverse">[@R-tidyverse]</span>, Bayesian modelling was done using the <code>brms</code> <span class="citation" data-cites="burkner2017brms carpenter2017stan">[@burkner2017brms; @carpenter2017stan]</span>, <code>loo</code> <span class="citation" data-cites="loo">[@loo]</span>, and <code>tidybayes</code> <span class="citation" data-cites="tidybayes">[@tidybayes]</span> R packages. Data and materials are available at OSF <a href="https://osf.io/hy984/">https://osf.io/hy984/</a>, and code is available at GitHub <a href="https://github.com/gongcastro/trajectories">https://github.com/gongcastro/trajectories</a>.</p>
</section>
</section>
<section id="sec-results" class="level1">
<h1>Results</h1>
<section id="sec-comparison" class="level2">
<h2 class="anchored" data-anchor-id="sec-comparison">Model comparison and selection</h2>
<p>The extended model (<span class="math inline">\(\mathcal{M}_{4}\)</span>), which included the three-way interaction between <span class="math inline">\(Age\)</span>, <span class="math inline">\(DoE\)</span>, and <span class="math inline">\(Levenshtein\)</span> showed the best predictive performance, with a difference in expected log-predicted density (<em>ELPD</em>) compared to the other models several times larger than the standard error of such difference <a href="#tbl-results-loos">see&nbsp;3</a>. This indicates that, given the data, the predictions of the <span class="math inline">\(\mathcal{M}_{4}\)</span> are confidently more accurate than those of the other models.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-results-loos" class="anchored">

<div id="tszlcfrjdy" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#tszlcfrjdy) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#tszlcfrjdy) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#tszlcfrjdy) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#tszlcfrjdy) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#tszlcfrjdy) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#tszlcfrjdy) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#tszlcfrjdy) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#tszlcfrjdy) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#tszlcfrjdy) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#tszlcfrjdy) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#tszlcfrjdy) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#tszlcfrjdy) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#tszlcfrjdy) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#tszlcfrjdy) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#tszlcfrjdy) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#tszlcfrjdy) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#tszlcfrjdy) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#tszlcfrjdy) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#tszlcfrjdy) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#tszlcfrjdy) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#tszlcfrjdy) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#tszlcfrjdy) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#tszlcfrjdy) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#tszlcfrjdy) .gt_left {
  text-align: left;
}

:where(#tszlcfrjdy) .gt_center {
  text-align: center;
}

:where(#tszlcfrjdy) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#tszlcfrjdy) .gt_font_normal {
  font-weight: normal;
}

:where(#tszlcfrjdy) .gt_font_bold {
  font-weight: bold;
}

:where(#tszlcfrjdy) .gt_font_italic {
  font-style: italic;
}

:where(#tszlcfrjdy) .gt_super {
  font-size: 65%;
}

:where(#tszlcfrjdy) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#tszlcfrjdy) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#tszlcfrjdy) .gt_indent_1 {
  text-indent: 5px;
}

:where(#tszlcfrjdy) .gt_indent_2 {
  text-indent: 10px;
}

:where(#tszlcfrjdy) .gt_indent_3 {
  text-indent: 15px;
}

:where(#tszlcfrjdy) .gt_indent_4 {
  text-indent: 20px;
}

:where(#tszlcfrjdy) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table"><caption>Table&nbsp;3:  Bayesian leave-one-out cross validation (LOO-CV). The predictive accuracy of the models was compared using leave-one-out cross-validation. The likelihood of each data point given a model fitted without including that same observation was estimated. The resulting likelihoods of each model were summarised as its expected log-predicted density (ELPD), which penalises the complexity of each model. ELPD values closer to zero indicate better predictive acuracy. We report the ELPD, effective number of parameters (p), and information criterion (IC) of each model along their associated standard errors (SE). The last column indicates the difference in ELPD between each model and the model with the best predictive accuracy (model 3). </caption>
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col" id="Model">Model</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" style="font-weight: bold;" scope="colgroup" id="LOO<sub>ELPD</sub>">
        <span class="gt_column_spanner">LOO<sub>ELPD</sub></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" style="font-weight: bold;" scope="colgroup" id="LOO<sub>p</sub>">
        <span class="gt_column_spanner">LOO<sub>p</sub></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" style="font-weight: bold;" scope="colgroup" id="LOO<sub>IC</sub>">
        <span class="gt_column_spanner">LOO<sub>IC</sub></span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" style="font-weight: bold;" scope="colgroup" id="LOO<sub>diff</sub>">
        <span class="gt_column_spanner">LOO<sub>diff</sub></span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="<em>ELPD</em>"><em>ELPD</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="<em>SE</em>"><em>SE</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="<em>p</em>"><em>p</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="<em>SE</em>"><em>SE</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="<em>LOO-IC</em>"><em>LOO-IC</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="<em>SE</em>"><em>SE</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="<em>diff</em>"><em>diff</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="<em>SE</em>"><em>SE</em></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="model" class="gt_row gt_right">4</td>
<td headers="elpd_loo" class="gt_row gt_right">−143,058.13</td>
<td headers="se_elpd_loo" class="gt_row gt_right">319.55</td>
<td headers="p_loo" class="gt_row gt_right">1,548.11</td>
<td headers="se_p_loo" class="gt_row gt_right">6.32</td>
<td headers="looic" class="gt_row gt_right">286,116.26</td>
<td headers="se_looic" class="gt_row gt_right">639.10</td>
<td headers="elpd_diff" class="gt_row gt_right">0.00</td>
<td headers="se_diff" class="gt_row gt_right">0.00</td></tr>
    <tr><td headers="model" class="gt_row gt_right">3</td>
<td headers="elpd_loo" class="gt_row gt_right">−143,129.18</td>
<td headers="se_elpd_loo" class="gt_row gt_right">319.41</td>
<td headers="p_loo" class="gt_row gt_right">1,484.72</td>
<td headers="se_p_loo" class="gt_row gt_right">5.58</td>
<td headers="looic" class="gt_row gt_right">286,258.36</td>
<td headers="se_looic" class="gt_row gt_right">638.82</td>
<td headers="elpd_diff" class="gt_row gt_right">−71.05</td>
<td headers="se_diff" class="gt_row gt_right">42.98</td></tr>
    <tr><td headers="model" class="gt_row gt_right">2</td>
<td headers="elpd_loo" class="gt_row gt_right">−143,569.91</td>
<td headers="se_elpd_loo" class="gt_row gt_right">320.73</td>
<td headers="p_loo" class="gt_row gt_right">1,592.23</td>
<td headers="se_p_loo" class="gt_row gt_right">5.90</td>
<td headers="looic" class="gt_row gt_right">287,139.82</td>
<td headers="se_looic" class="gt_row gt_right">641.47</td>
<td headers="elpd_diff" class="gt_row gt_right">−511.78</td>
<td headers="se_diff" class="gt_row gt_right">66.67</td></tr>
    <tr><td headers="model" class="gt_row gt_right">1</td>
<td headers="elpd_loo" class="gt_row gt_right">−143,659.36</td>
<td headers="se_elpd_loo" class="gt_row gt_right">315.38</td>
<td headers="p_loo" class="gt_row gt_right">1,267.71</td>
<td headers="se_p_loo" class="gt_row gt_right">5.38</td>
<td headers="looic" class="gt_row gt_right">287,318.72</td>
<td headers="se_looic" class="gt_row gt_right">630.76</td>
<td headers="elpd_diff" class="gt_row gt_right">−601.23</td>
<td headers="se_diff" class="gt_row gt_right">60.60</td></tr>
    <tr><td headers="model" class="gt_row gt_right">0</td>
<td headers="elpd_loo" class="gt_row gt_right">−144,812.68</td>
<td headers="se_elpd_loo" class="gt_row gt_right">315.50</td>
<td headers="p_loo" class="gt_row gt_right">890.44</td>
<td headers="se_p_loo" class="gt_row gt_right">3.04</td>
<td headers="looic" class="gt_row gt_right">289,625.36</td>
<td headers="se_looic" class="gt_row gt_right">631.01</td>
<td headers="elpd_diff" class="gt_row gt_right">−1,754.55</td>
<td headers="se_diff" class="gt_row gt_right">84.70</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="9">Pareto-<em>k</em> estimates of all models were acceptable (<em>k</em> &lt; 0.5)</td>
    </tr>
  </tfoot>
  
</table>
</div>
</div>
</div>
</div>
</section>
<section id="sec-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="sec-coefficients">Regression coefficients</h2>
<div class="cell">

</div>
<p><a href="#tbl-results-fixed">Table&nbsp;4</a> shows the summary of the posterior distribution of the fixed regression coefficients of the selected model. For interpretability, we supplement the summaries of each posterior regression coefficient with its transformation to the probability scale. The resulting values correspond to the maximum difference in probability of acquisition (<em>Comprehension</em> or <em>Comprehension and Production</em>) that corresponds to a one standard deviation change in each predictor<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-results-fixed" class="anchored">

<div id="mcyioixgsh" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#mcyioixgsh) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#mcyioixgsh) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#mcyioixgsh) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#mcyioixgsh) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#mcyioixgsh) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#mcyioixgsh) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#mcyioixgsh) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#mcyioixgsh) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#mcyioixgsh) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#mcyioixgsh) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#mcyioixgsh) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#mcyioixgsh) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#mcyioixgsh) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#mcyioixgsh) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#mcyioixgsh) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#mcyioixgsh) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#mcyioixgsh) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#mcyioixgsh) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#mcyioixgsh) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#mcyioixgsh) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#mcyioixgsh) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#mcyioixgsh) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#mcyioixgsh) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#mcyioixgsh) .gt_left {
  text-align: left;
}

:where(#mcyioixgsh) .gt_center {
  text-align: center;
}

:where(#mcyioixgsh) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#mcyioixgsh) .gt_font_normal {
  font-weight: normal;
}

:where(#mcyioixgsh) .gt_font_bold {
  font-weight: bold;
}

:where(#mcyioixgsh) .gt_font_italic {
  font-style: italic;
}

:where(#mcyioixgsh) .gt_super {
  font-size: 65%;
}

:where(#mcyioixgsh) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#mcyioixgsh) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#mcyioixgsh) .gt_indent_1 {
  text-indent: 5px;
}

:where(#mcyioixgsh) .gt_indent_2 {
  text-indent: 10px;
}

:where(#mcyioixgsh) .gt_indent_3 {
  text-indent: 15px;
}

:where(#mcyioixgsh) .gt_indent_4 {
  text-indent: 20px;
}

:where(#mcyioixgsh) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table"><caption>Table&nbsp;4:  Posterior distribution of regression coefficients. Median: median of the posterior distribution in the logit scale. 95% HDI: 95% highest density interval (HDI) of the distribution; narrowest range of values that contains 95% of the distribution, and therefore is 95% likely to contain the true value, given the data. ROPE Prob.: percentage of the posterior samples that fall within the region o practical equivalence (ROPE, [-0.1, 0.1] in the logit scale); posterior probability of the true value of the parameter being equivalent to zero. </caption>
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="font-weight: bold;" scope="col" id="Parameter">Parameter</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-weight: bold;" scope="col" id="Median">Median</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-weight: bold;" scope="col" id="95% <em>HDI</em>">95% <em>HDI</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="font-weight: bold;" scope="col" id="<em>ROPE</em> prob."><em>ROPE</em> prob.</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="parameter" class="gt_row gt_left">Intercept (Comprehension and Production at 22 months)</td>
<td headers="median" class="gt_row gt_right">−1.32</td>
<td headers="ci_low" class="gt_row gt_right">[−1.44, −1.20]</td>
<td headers="rope_percentage" class="gt_row gt_right">0.00%</td></tr>
    <tr><td headers="parameter" class="gt_row gt_left">Intercept (Comprehension at 22 months)</td>
<td headers="median" class="gt_row gt_right">1.62</td>
<td headers="ci_low" class="gt_row gt_right">[1.50, 1.74]</td>
<td headers="rope_percentage" class="gt_row gt_right">0.00%</td></tr>
    <tr><td headers="parameter" class="gt_row gt_left">Age (+1 SD, 4.81 months)</td>
<td headers="median" class="gt_row gt_right">1.55</td>
<td headers="ci_low" class="gt_row gt_right">[1.36, 1.73]</td>
<td headers="rope_percentage" class="gt_row gt_right">0.00%</td></tr>
    <tr><td headers="parameter" class="gt_row gt_left">NA</td>
<td headers="median" class="gt_row gt_right">0.80</td>
<td headers="ci_low" class="gt_row gt_right">[0.67, 0.95]</td>
<td headers="rope_percentage" class="gt_row gt_right">0.00%</td></tr>
    <tr><td headers="parameter" class="gt_row gt_left">Levenshtein (+1 SD, 26%)</td>
<td headers="median" class="gt_row gt_right">0.09</td>
<td headers="ci_low" class="gt_row gt_right">[−0.07, 0.25]</td>
<td headers="rope_percentage" class="gt_row gt_right">56.74%</td></tr>
    <tr><td headers="parameter" class="gt_row gt_left">Phonemes (+1 SD, 1.56 phonemes)</td>
<td headers="median" class="gt_row gt_right">−0.30</td>
<td headers="ci_low" class="gt_row gt_right">[−0.40, −0.19]</td>
<td headers="rope_percentage" class="gt_row gt_right">0.00%</td></tr>
    <tr><td headers="parameter" class="gt_row gt_left">NA</td>
<td headers="median" class="gt_row gt_right">0.28</td>
<td headers="ci_low" class="gt_row gt_right">[0.13, 0.44]</td>
<td headers="rope_percentage" class="gt_row gt_right">0.00%</td></tr>
    <tr><td headers="parameter" class="gt_row gt_left">Age × Levenshtein</td>
<td headers="median" class="gt_row gt_right">0.05</td>
<td headers="ci_low" class="gt_row gt_right">[−0.01, 0.11]</td>
<td headers="rope_percentage" class="gt_row gt_right">97.26%</td></tr>
    <tr><td headers="parameter" class="gt_row gt_left">NA</td>
<td headers="median" class="gt_row gt_right">−0.23</td>
<td headers="ci_low" class="gt_row gt_right">[−0.27, −0.18]</td>
<td headers="rope_percentage" class="gt_row gt_right">0.00%</td></tr>
    <tr><td headers="parameter" class="gt_row gt_left">NA</td>
<td headers="median" class="gt_row gt_right">−0.08</td>
<td headers="ci_low" class="gt_row gt_right">[−0.11, −0.04]</td>
<td headers="rope_percentage" class="gt_row gt_right">88.47%</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
<p><span class="math inline">\(Age\)</span> was the predictor with the largest effect on the probability of acquisition (<span class="math inline">\(\beta\)</span> = 1.55, 95% <em>HDI</em> = [1.36, 1.73]): at the steepest point of the acquisition trajectory of an average translation equivalent, the probability of acquisition increased 8.05% every month. Lexical frequency (<span class="math inline">\(Frequency\)</span>) had a small, positive, but inconclusive on the probability of acquisition substantially, (<span class="math inline">\(\beta\)</span> = , 95% <em>HDI</em> = [, ]): of its posterior samples overlapped with the <em>ROPE.</em> The 95% <em>HDI</em> of the regression coefficient of the number of phonemes (<span class="math inline">\(Phonemes\)</span>) did exclude the <em>ROPE</em>, although not by much: 0.00% of its posterior samples fell within the <em>ROPE</em>. This suggests that the number of phonemes in the word form had a small effect on the probability of acquisition (<span class="math inline">\(\beta\)</span> = -30.13%, 95% <em>HDI</em> = [-40.11%, -18.91%]). For every increase in phoneme length, the probability of acquisition decreased in -4.83%.</p>
<div class="cell" data-fig.heigh="7">

</div>
<p>The degree of exposure to the language (<span class="math inline">\(DoE\)</span>) had a strong effect on the probability of acquisition (<span class="math inline">\(\beta\)</span> = , 95% <em>HDI</em> = [, ]). All of the posterior samples of his regression excluded the <em>ROPE</em>. The impact of this predictor on the probability of acquisition was positive: for every 10% increase in exposure to the language the word belongs to, the participant was more likely to acquire it. The effect of phonological similarity by itself (as indicated by the regression coefficient of the main effect of <span class="math inline">\(Levenshtein\)</span>) was equivalent to zero (<span class="math inline">\(\beta\)</span> = 8.72%, 95% <em>HDI</em> = [-6.69%, 25.04%]), as 56.74% of the posterior samples of its regression coefficient fell into the <em>ROPE</em>. However, the 95% <em>HDI</em> of the regression coefficient of the <span class="math inline">\(Doe \times Levenshtein\)</span> interaction excluded the <em>ROPE</em> entirely (<span class="math inline">\(\beta\)</span> = , 95% <em>HDI</em> = [, ]), suggesting that the effect of phonological similarity on a word’s probability of acquisition changed depending on participants’ exposure to the language it belonged to. Follow up analyses on this interaction (see <a href="#fig-results-marginal">Figure&nbsp;1</a>) showed that, when exposure to the language was low (e.g., 10%), phonological similarity increased the probability of acquisition substantially. This effect was negligible when exposure to both languages was balanced (e.g.&nbsp;50-50%). Finally, when exposure to the language was high (e.g., 90%), this effect was very close to zero, although with different direction, with phonological less similar translation equivalents being more likely to be acquired than phonologically more similar ones.</p>
<p>The 95% <em>HDI</em> of the regression coefficient of the <span class="math inline">\(Age \times DoE\)</span> interaction did not exclude the <em>ROPE</em> (<span class="math inline">\(\beta\)</span> = , 95% <em>HDI</em> = [, ]): of its posterior samples fell within the <em>ROPE</em>. This shows that the effect of the degree of exposure on the speed at which participants acquired word across ages was inconclusive. Give our data, it is difficult to tell whether this <em>DoE</em> increased or decreased the slope of the words’ acquisition trajectories. The 95% <em>HDI</em> of the regression coefficient of the <span class="math inline">\(Age \times Levenshtein\)</span> interaction overlapped completely with the <em>ROPE</em> (<span class="math inline">\(\beta\)</span> = 5.20%, 95% <em>HDI</em> = [-0.70%, 10.67%]), indicating that phonological similarity did not speed-up the acquisition trajectories of the words across ages. Finally, the 95% <em>HDI</em> of the regression coefficient of the <span class="math inline">\(Age \times DoE \times Levenshtein\)</span> interaction also overlapped completely with the <em>ROPE</em> (<span class="math inline">\(\beta\)</span> = , 95% <em>HDI</em> = [, ]), suggesting that the impact of the degree of exposure to the language on the effect of phonological similarity did not differ substantially across ages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>nd <span class="ot">&lt;-</span> <span class="fu">datagrid</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">model =</span> model_fit_4,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_std =</span> <span class="fu">seq_range</span>(model_fit_4<span class="sc">$</span>data<span class="sc">$</span>age_std, <span class="at">n =</span> <span class="dv">100</span>),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lv_std =</span> (<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.5</span>)<span class="sc">-</span><span class="fu">mean</span>(df<span class="sc">$</span>lv))<span class="sc">/</span>(<span class="fu">sd</span>(df<span class="sc">$</span>lv)),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">exposure_std =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">te =</span> <span class="cn">NA</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">id =</span> <span class="cn">NA</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>marg_epreds <span class="ot">&lt;-</span> <span class="fu">predictions</span>(</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    model_fit_4,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">newdata =</span> nd,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">ndraws =</span> <span class="dv">25</span>, </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">re_formula =</span> <span class="cn">NA</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>marg_epreds <span class="sc">%&gt;%</span> </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">posteriordraws</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(drawid, group, draw, age_std, lv_std, exposure_std) <span class="sc">%&gt;%</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(group <span class="sc">!=</span> <span class="st">"No"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">id_cols =</span> <span class="fu">c</span>(drawid, age_std, lv_std, exposure_std), </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">names_from =</span> group, </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>        <span class="at">values_from =</span> draw</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Understands</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">Understands and Says</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Understands</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="fu">c</span>(<span class="st">`</span><span class="at">Understands</span><span class="st">`</span>, <span class="st">`</span><span class="at">Understands and Says</span><span class="st">`</span>), <span class="at">names_to =</span> <span class="st">"group"</span>, <span class="at">values_to =</span> <span class="st">"draw"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>        <span class="at">exposure_std =</span> <span class="fu">factor</span>(</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>            exposure_std, </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">levels =</span> <span class="fu">unique</span>(nd<span class="sc">$</span>exposure_std), </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Exposure: -1 SD"</span>, <span class="st">"Exposure: mean"</span>, <span class="st">"Exposure: +1 SD"</span>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>        <span class="at">lv_std =</span> <span class="fu">factor</span>(</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>            lv_std,</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>            <span class="at">levels =</span> <span class="fu">unique</span>(nd<span class="sc">$</span>lv_std), </span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels =</span> <span class="fu">paste0</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">50</span>, <span class="dv">100</span>), <span class="st">"% similarity"</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(age_std, draw, <span class="at">colour =</span> lv_std, <span class="at">fill =</span> lv_std)) <span class="sc">+</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_grid</span>(group<span class="sc">~</span>exposure_std) <span class="sc">+</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="co"># stat_summary(fun.data = median_hdi, geom = "ribbon",</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    <span class="co">#              alpha = 0.5, colour = NA) +</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="fu">interaction</span>(lv_std, drawid)),</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.75</span>, <span class="at">alpha =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">linetype =</span> lv_std), <span class="at">fun =</span> median, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span> <span class="st">"Age (months)"</span>,</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Probability of acquisition"</span>,</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>        <span class="at">linetype =</span> <span class="st">"Phonological similarity (Levenshtein)"</span>,</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>        <span class="at">colour =</span> <span class="st">"Phonological similarity (Levenshtein)"</span>,</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>        <span class="at">fill =</span> <span class="st">"Phonological similarity (Levenshtein)"</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> clrs[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">5</span>)]) <span class="sc">+</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> clrs[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">5</span>)]) <span class="sc">+</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>        <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.25</span>),</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>        <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>        <span class="at">labels =</span> percent</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>        <span class="at">breaks =</span> (<span class="fu">seq</span>(<span class="dv">10</span>, <span class="dv">32</span>, <span class="dv">4</span>)<span class="sc">-</span><span class="fu">mean</span>(df<span class="sc">$</span>age))<span class="sc">/</span>(<span class="fu">sd</span>(df<span class="sc">$</span>age)),</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>        <span class="at">labels =</span> <span class="fu">seq</span>(<span class="dv">10</span>, <span class="dv">32</span>, <span class="dv">4</span>)</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">0.75</span>)</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-results-marginal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="manuscript_files/figure-html/fig-results-marginal-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Expected posterior predictions. Posterior predictions for the extended model were generated by computing the probability acquisition that resulted from feeding the equation of the regression model with values of the posterior distribution of each coefficient. These values correspond to the 4,000 samples of the posterior distribution that were drawn during the MCMC estimation of the model. Therefore, we generated 4,000 predictions for a series of combination of levels of interest. Each line and interval and in the figure summarises the mean and 95% <em>HDI</em> of each combination of levels. The X-axis indicates the age (in months) for which the prediction is generated. The Y-axis indicates the predicted probability of acquisition (<em>Comprehension</em> or <em>Comprehension and Production</em>). Different colours indicate different levels of phonological similarity (as indicated by the Levenshtein similarity between pairs of translation equivalents). Finally, predictions are presented separately for different degrees of exposure (10%): little exposure to the language (10% DoE, traditionally classified as monolingual), balanced exposure to both languages (50%, traditionally classified as bilingual), and high exposure to the language (90%, traditionally classified as monolingual). Predictions for <em>Comprehension</em> are show on top and predictions for <em>Comprehension and Production</em> are shown on the bottom.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-discussion" class="level1">
<h1>Discussion</h1>
<section id="summary-of-the-study" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-the-study">Summary of the study</h2>
<ul>
<li>This study explored how word acquisition is affected by cognateness in bilingual toddlers.</li>
<li>We collected vocabulary data from children learning Catalan and/or Spanish in differing degrees of exposure to each, and then measured the probability of each word being acquired at different ages as a function of (1) participants’ exposure to the language it belongs to, and (2) its phonological similarity with its translation equivalent in the other language.</li>
<li>Using item response theory (<em>IRT</em>), we built an Bayesian model that estimated the effect of both predictors and their interaction, adjusting for other variables known to be relevant for the acquisition of words: participants’ age, lexical frequency, and word length in phonemes.</li>
</ul>
</section>
<section id="summary-of-results-and-contrast-with-the-literature" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-results-and-contrast-with-the-literature">Summary of results and contrast with the literature</h2>
<ul>
<li>We replicated effects reported in previous studies, such as age being the most determinant predictor of word acquisition, followed by exposure to the language, that frequent words are acquired earlier, and that word length predicts a later age of acquisition.</li>
<li>Regarding our hypotheses, we found strong evidence for a two-way interaction between language exposure and phonological similarity: participants were more likely to acquire word-forms from cognate translation equivalents than from non-cognate translation equivalents, but only when their exposure to the language of such word-form was low.</li>
<li>Our results converge with previous findings indicating that phonological similarity between translation equivalents plays a facilitation role in word acquisition, but suggest that this effect is mostly, or only present in participants’ language of lower exposure.</li>
</ul>
</section>
<section id="mechanistic-explanations" class="level2">
<h2 class="anchored" data-anchor-id="mechanistic-explanations">Mechanistic explanations</h2>
<ul>
<li>These findings support the hypothesis that the cognate facilitation effect on word acquisition is more likely to play such role <em>after</em> one of the word-forms of the translation equivalent has been acquired in one of the languages, as opposed to taking place before any of the forms has been acquired, by promoting their acquisition though cross-language activation at the sub-lexical, phonological level.</li>
<li>In line with the first hypothesis, words in the language of higher exposure are likely to be acquired earlier than those in the language of lower exposure, and also showed a larger effect facilitation effect of cognateness.</li>
<li>This suggests that cognateness might have played a larger role during the acquisition of words from the language of lower exposure than from the language of higher exposure in bilinguals</li>
</ul>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<ul>
<li>These results come from a particular population of bilingual toddlers that learn two very similar languages–Catalan and Spanish–and are therefore exposed to many cognates. Our results might not generalise to other groups of bilinguals learning two less similar languages.</li>
<li>[To be discussed]</li>
</ul>
</section>
<section id="further-steps" class="level2">
<h2 class="anchored" data-anchor-id="further-steps">Further steps</h2>
<ul>
<li>[To be discussed]</li>
</ul>
</section>
</section>
<section id="sec-references" class="level1">
<h1>References</h1>
<div id="refs" role="doc-bibliography">

</div>
</section>
<section id="sec-appendix" class="level1">
<h1>Appendix</h1>
<section id="sec-appendix-words" class="level2">
<h2 class="anchored" data-anchor-id="sec-appendix-words">Appendix 1: Words</h2>
<div class="cell" data-lab="tbl-appendix-words" data-tbl-cap="Words included in the analysis">

</div>
</section>
<section id="sec-appendix-model" class="level2">
<h2 class="anchored" data-anchor-id="sec-appendix-model">Appendix 2: Model details</h2>
</section>
<section id="sec-appendix-rope" class="level2">
<h2 class="anchored" data-anchor-id="sec-appendix-rope">Appendix 3: <em>ROPE</em> specification</h2>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Due to computational constraints, we performed LOO based on a random sub-sample of 700 samples of the posterior distribution of the fixed effects <span class="citation" data-cites="magnusson2019bayesian">[@magnusson2019bayesian]</span><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>For example, a 90% overlap between the <em>HDI</em> of the coefficients’ posterior distribution and the <em>ROPE</em> indicates that, given our data, there is a 90% probability that the true value of the coefficient falls within the <em>ROPE</em>, and is therefore equivalent to zero<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The logit and probability scales related non-linearly. This means that one logit difference is not necessarily translated to a unique value in the probability scale. For example, the probability of acquisition of a given word might increase in 5% when age increases from 22 to 23 months, the probability of acquisition of the same word might only increase in 0.2% when age increases from 34 to 36 months. The linear growth of the probability of acquisition differs along the logistic curve, and therefore deciding the age point at which to report the estimates of the regression coefficients in the probability scale is not trivial. We followed the suggestion by <span class="citation" data-cites="gelman2020regression">@gelman2020regression</span> and report the maximum value of such coefficient, which corresponds to the linear growth (i.e., derivative) of the logistic curve at the age at which most participants were acquiring a given word. This value can be approximated by dividing the coefficient in the logit scale by four: <span class="math inline">\(\hat{\beta_j}/4\)</span>, where <span class="math inline">\(\hat{\beta_j}\)</span> is the estimated mean of the posterior distribution of coefficient <span class="math inline">\(j\)</span>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>