---
appendix: trajectories_manuscript_appendix.Rmd
output: pdf_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

dat_wordbank <- fread(here("Data", "05_wordbank.csv"))
dat_wordbank_priors <- fread(here("Data", "05_priors-wordbank.csv"))
```

We fitted a logistic model using the proportion of infants that acquired each item as output, and age-bin (defined as we did with our data) as input, estimating the three parameters afore mentioned (asymptote, mid-point, and steepness). We included data from `r nrow(dat_wordbank)/length(unique(dat_wordbank$age)) %>% printnum()` items from `r dat_wordbank$language %>% unique %>% length` languages^[Chinese (Cantonese and Mandarin), Croatian, Czech, Danish, English (Australian, British, and American), French (European), German, Hebrew, Italian, Korean, Latvian, Portuguese, Russian, Slovak, Spanish (European and Mexican), and Turkish. All the other available languages were excluded, as no (or insufficient) data were available.], from monolingual infants aged 16 to 30 months of age.



**Figure caption**: "Logarithmic model fitted on Wordbank data, compared to a linear model. The logarithmic model fits the data slightly better. The estimated values of the three parameters involved in the logarithmic model (asymptote, mid-point and steepness) are indicated."
