#' Generate posterior predictions for fixed effects brmsfit model via \code{marginaleffects::predictions}
#'
#' @param model A brmsfit object
#' @param data Data with the desired combination of levels of the predictors for which to generate posterior predictions, as generated by \code{generate_newdata}
#' @param group Group level for which posterior predictions are generated. Takes 'te' or 'id' as values.
#' @param ... Additional arguments passed to \code{marginaleffects::predictions}
get_mid <- function(model, newdata, x) {
    
    coefs <- coef(model)
    x_index <- which(names(coefs[-1]) == x)
    nd <- newdata[, names(newdata)]
    
    formula_terms <- drop.terms(terms(model$formula), x_index)
    formula_2 <- reformulate(attr(formula_terms, "term.labels"))
    
    m_frame <- unique(model.frame(formula_2, nd))
    mat <- model.matrix(formula_2, m_frame[, names(m_frame)!=x])
    mat_names <- attr(mat, "dimnames")[[2]]
    
    coefs_nd <- coefs[names(coefs) != x]
    
    linear <- as.numeric(mat %*% coefs_nd)
    midpoint <- -(linear) / coef(model)[x]
    
    return(midpoint)
}