
#' Specify and sample a [brms::brm()] model
#' @param name A character string indicating the name to be assigned to the model
#' @param ... Arguments to be passed to [brms::brm()]
fit_model <- function(name, ...) 
{
    fit <- brm(...,
               iter = 2000,
               chains = 4,
               init = 0.5,
               seed = 888,
               threads = threading(4),
               backend = "cmdstanr",
               file = glue("results/fits/{name}.rds"),
               file_refit = "on_change",
               control = list(adapt_delta = 0.9,
                              max_treedepth = 15),
               save_model = glue("stan/{name}.stan"))
    
    return(fit)
}

#' Dictionary for predictor names
#' 
#' @param data Dataset of responses as generated by the [get_responses()] function
#' @returns A named character vector
get_vars_dict <- function(responses) 
{
    c(
        "b_Intercept[1]" = "Comprehension and Production",
        "b_Intercept[2]" = "Comprehension",
        "b_age_std" = glue("Age (+1 SD, {round(sd(responses$age), 2)}, months)"),
        "b_n_phon_std" = glue("Length (+1 SD, {round(sd(responses$n_phon), 2)} phonemes)"),
        "b_exposure_std" = glue("Exposure (+1 SD, {round(sd(responses$exposure), 2)})"),
        "b_lv_std" = glue("Cognateness (+1 SD, {percent(sd(responses$lv), accuracy = 0.01)})"),
        "b_exposure_std:lv_std" = "Exposure \u00d7 Cognateness",
        "b_age_std:exposure_std" = "Age \u00d7 Exposure",
        "b_age_std:lv_std" = "Age \u00d7 Cognateness",
        "b_age_std:exposure_std:lv_std" = "Age \u00d7 Exposure \u00d7 Cognateness"
    )
}

#' Extract posterior draws of fixed effect coefficients from brmsfit model via [tidybayes::gather_draws()].
#' 
#' @param model A brmsfit object
#' @param data Dataset of responses as generated by the [get_responses()] function
#' @param ... Arguments to be passed to [tidybayes::gather_draws()].
get_posterior_draws <- function(model, data, var_dict, ...)
{
    # tidy predictor names
    str_repl <- c(
        "b_Intercept[1]" = "Comprehension and Production",
        "b_Intercept[2]" = "Comprehension",
        "b_age_std" = glue("Age (+1 SD, {round(sd(data$age), 2)}, months)"),
        "b_n_phon_std" = glue("Length (+1 SD, {round(sd(data$n_phon), 2)} phonemes)"),
        "b_exposure_std" = glue("Exposure (+1 SD, {round(sd(data$exposure), 2)})"),
        "b_lv_std" = glue("Cognateness (+1 SD, {percent(sd(data$lv), accuracy = 0.01)})"),
        "b_exposure_std:lv_std" = "Exposure \u00d7 Cognateness",
        "b_age_std:exposure_std" = "Age \u00d7 Exposure",
        "b_age_std:lv_std" = "Age \u00d7 Cognateness",
        "b_age_std:exposure_std:lv_std" = "Age \u00d7 Exposure \u00d7 Cognateness"
    )
    
    # posterior draws
    posterior_draws <- gather_draws(model, `b_.*`, regex = TRUE, ...) |>
        mutate(.variable_name = factor(.variable,
                                       levels = names(var_dict),
                                       labels = var_dict) |>
                   as.character(),
               type = ifelse(str_detect(.variable, "Intercept"),
                             glue("Intercepts (at {round(mean(data$age, 2))} months)"),
                             "Slopes"),
               parameter = ifelse(str_detect(.variable, "Intercept"),
                                  str_remove_all(.variable, "Intercept \\(|\\)"),
                                  .variable)) |>
        select(.variable, .variable_name, .type = type, 
               .chain, .iteration, .draw, .value) |>
        ungroup()
    
    save_files(posterior_draws, 
               formats = "csv",
               folder = "results/posterior")
    
    return(posterior_draws)
}

#' Extract posterior draws of fixed effect coefficients from brmsfit model via [tidybayes::gather_draws()].
#' 
#' @param model A brmsfit object
#' @param data Dataset of responses as generated by the [get_responses()] function
#' @param ... Arguments to be passed to [tidybayes::gather_draws()].
get_posterior_summary <- function(model, data, var_dict,
                                  rope_interval = c(lower = -0.1,
                                                    upper = +0.1),
                                  ...) 
{
    
    # posterior summary
    posterior_summary <- describe_posterior(model,
                                            test = "rope",
                                            rope_range = rope_interval,
                                            ci_method = "HDI",
                                            ...) |>
        as_tibble() |>
        clean_names() |>
        mutate(.variable_name = factor(parameter,
                                       levels = names(var_dict),
                                       labels = as.character(var_dict)),
               type = ifelse(str_detect(parameter, "Intercept"),
                             glue("Intercepts (at {round(mean(data$age, 2))} months)"),
                             "Slopes"),
               parameter = ifelse(str_detect(parameter, "Intercept"),
                                  str_remove_all(parameter, "Intercept \\(|\\)"),
                                  parameter)
        ) |>
        select(.variable = parameter,
               .variable_name,
               .type = type,
               .median = median,
               .upper = ci_high,
               .lower = ci_low,
               .rope_overlap = rope_percentage
        ) |>
        ungroup()
    
    return(posterior_summary)
}

#' Extract posterior draws of random effect coefficients (a.k.a. group-level coefficients) from brmsfit model via [tidybayes::gather_draws()].
#' 
#' @param model A brmsfit object
#' @param data Dataset of responses as generated by the [get_responses()].
#' @param ... Arguments to be passed to [tidybayes::gather_draws()].
get_posterior_draws_re <- function(model)
{
    # get posterior draws of dixed effects
    posterior_draws <- gather_draws(model, `b_.*`, regex = TRUE) |>
        rename(.value_fixed = .value) |>
        mutate(
            .type = case_when(
                .variable == "b_Intercept[2]" ~ "Comprehension",
                .variable == "b_Intercept[1]" ~ "Comprehension and Production",
                TRUE ~ "Both"
            ),
            .variable = str_remove_all(.variable, "b_|\\[1\\]|\\[2\\]")
        )
    
    # get posterior draws of random effects
    posterior_draws_re <- gather_draws(model, r_te[te, term]) |>
        ungroup() |>
        select(-.variable) |>
        rename(.variable = term) |>
        left_join(posterior_draws,
                  by = join_by(.variable, .chain, .iteration, .draw)) |>
        mutate(.value_rescaled = .value + .value_fixed)
    
    # export draws
    save_files(posterior_draws_re, 
               formats = "csv",
               folder = "results/posterior")
    
    return(posterior_draws_re)
}

#' Get model R-hat scores
#' 
#' @param model A brmsfit object
#' @param ... Arguments to be passed to [bayesplot::rhat()] and 
#' [bayesplot::neff_ratio()].
#' 
#' @returns A [tibble::tibble] with three columns:
#' * .variable: parameter names, as returned by [brms::variables()]
#' * .rhat: R-hat (Gelman-Rubin) convergence diagnostic, as returned by 
#' [bayesplot::rhat()].
#' * .neff: effective sample size, as returned by [bayesplot::neff_ratio()]
get_model_convergence <- function(model, ...) 
{
    tibble(.variable = variables(model), 
           .rhat = brms::rhat(model, ...),
           .neff = brms::neff_ratio(model, ...))
}

#' Get model posterior predictive checks
#' 
#' @param model A brmsfit object
#' @param ... Arguments to be passed to [brms::posterior_predict()].
#' 
get_model_ppc <- function(model, ...)
{
    posterior_predict(model, ndraws = 100, cores = 4)
}